project_id = "sdegiugcttarbsnqvusm"
[functions.finance-api]
verify_jwt = false
[functions.line-webhook]
verify_jwt = false

[functions.account-access]
verify_jwt = false

[functions.line-login]
verify_jwt = false
