begin;
do $$
declare actor_id uuid; member_id uuid; rid uuid; cid uuid; paid_id uuid; replacement_id uuid; pending_id uuid; newer_pending uuid; eid uuid; blocked boolean; audit_count int;
begin
 select id into actor_id from profiles where role='admin' and active and deleted_at is null limit 1;
 select id into member_id from profiles where role='member' and active and deleted_at is null limit 1;
 if actor_id is null or member_id is null then raise exception 'Missing test actors';end if;
 rid:=create_round('ROLLBACK deletion test','test',100,current_date,'test');
 select id into cid from charges where round_id=rid and profile_id=member_id;
 paid_id:=reserve_payment(member_id,cid,40);
 update payments set drive_file_id='rollback-evidence' where id=paid_id;
 perform decide_payment(paid_id,'approved','test','delete-test-'||paid_id::text,actor_id);
 perform delete_records('payment',array[paid_id],true,'test deletion',actor_id);
 replacement_id:=reserve_payment(member_id,cid,100);
 update payments set drive_file_id='rollback-evidence' where id=replacement_id;
 perform decide_payment(replacement_id,'approved','test','replacement-'||replacement_id::text,actor_id);
 blocked:=false;
 begin perform delete_records('payment',array[paid_id],false,'restore test',actor_id);exception when others then if sqlerrm like '%เกินยอด%' then blocked:=true;else raise;end if;end;
 if not blocked then raise exception 'Overpayment restoration was allowed';end if;
 perform delete_records('payment',array[replacement_id],true,'remove replacement',actor_id);
 perform delete_records('payment',array[paid_id],false,'restore original',actor_id);
 if (select sum(amount) from payments where charge_id=cid and status='approved' and deleted_at is null)<>40 then raise exception 'Restored income incorrect';end if;
 if (select drive_file_id from payments where id=paid_id)<>'rollback-evidence' then raise exception 'Evidence lost';end if;
 pending_id:=reserve_payment(member_id,cid,20);
 perform delete_records('payment',array[pending_id],true,'delete pending',actor_id);
 newer_pending:=reserve_payment(member_id,cid,10);
 blocked:=false;
 begin perform delete_records('payment',array[pending_id],false,'restore pending',actor_id);exception when others then if sqlerrm like '%รอตรวจ%' then blocked:=true;else raise;end if;end;
 if not blocked then raise exception 'Duplicate pending restore was allowed';end if;
 perform delete_records('payment',array[newer_pending],true,'delete replacement',actor_id);
 perform delete_records('payment',array[pending_id],false,'restore pending',actor_id);
 perform delete_records('round',array[rid],true,'delete round',actor_id);
 blocked:=false;
 begin perform reserve_payment(member_id,cid,10);exception when others then if sqlerrm like '%ปิดรับชำระ%' then blocked:=true;else raise;end if;end;
 if not blocked then raise exception 'Deleted round accepts new money';end if;
 perform delete_records('round',array[rid],false,'restore round',actor_id);
 perform delete_records('member',array[member_id],true,'delete member',actor_id);
 if exists(select 1 from profiles where id=member_id and active and deleted_at is null) then raise exception 'Deleted user remains authorized';end if;
 blocked:=false;
 begin perform reserve_payment(member_id,cid,10);exception when others then if sqlerrm like '%บัญชีถูกปิด%' then blocked:=true;else raise;end if;end;
 if not blocked then raise exception 'Deleted user can reserve payment';end if;
 eid:=create_round('ROLLBACK exclusion test','test',25,current_date,'test');
 if exists(select 1 from charges where round_id=eid and profile_id=member_id) then raise exception 'Deleted member added to new round';end if;
 perform delete_records('member',array[member_id],false,'restore member',actor_id);
 blocked:=false;
 begin perform delete_records('member',array[actor_id],true,'self delete',actor_id);exception when others then if sqlerrm like '%ตนเอง%' then blocked:=true;else raise;end if;end;
 if not blocked then raise exception 'Admin self deletion allowed';end if;
 insert into expenses(title,category,amount,spent_on,created_by,drive_file_id) values('ROLLBACK expense','test',50,current_date,actor_id,'kept') returning id into eid;
 perform delete_records('expense',array[eid],true,'delete expense',actor_id);
 if exists(select 1 from expenses where id=eid and not voided and deleted_at is null) then raise exception 'Deleted expense counted';end if;
 perform delete_records('expense',array[eid],false,'restore expense',actor_id);
 if not exists(select 1 from audit where details->'before'->>'id'=eid::text and action like 'ลบ %') then raise exception 'Deletion audit missing';end if;
 if has_function_privilege('anon','public.delete_records(text,uuid[],boolean,text,uuid)','execute') or has_function_privilege('authenticated','public.update_own_profile(uuid,text,text,text,text)','execute') then raise exception 'Private RPC grants unsafe';end if;
 perform update_own_profile(member_id,'test edited name','2','0123456789','test@example.invalid');
 if not exists(select 1 from profiles where id=member_id and phone='0123456789' and year='2' and role='member') then raise exception 'Self profile update failed';end if;
end $$;
rollback;
select 'passed: delete/restore financial totals, retained evidence, pending uniqueness, parent deletion, user access, self protection, audit, profile update and grants; all test changes rolled back' as result;
