const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),esbuild=require('esbuild');
const out={exports:{}};vm.runInNewContext(esbuild.transformSync(fs.readFileSync('supabase/functions/_shared/evidence-storage.ts','utf8'),{loader:'ts',format:'cjs'}).code,{module:out,exports:out.exports,crypto,Response,Date,Error});const api=out.exports;
let rows,objects,jobs,audits,locked,failDelete,events;
const reset=()=>{rows=[];objects=new Map();jobs=[];audits=[];locked=false;failDelete=false;events=[]};reset();
const q=(table)=>{let filters=[],mode='select',patch,limit=1e4,sort='';const b={select(){return b},eq(k,v){filters.push(r=>r[k]===v);return b},lt(k,v){filters.push(r=>r[k]<v);return b},like(k,v){filters.push(r=>r[k].startsWith(v.replace('%','')));return b},order(k){sort=k;return b},limit(n){limit=n;return b},maybeSingle(){b.single=true;return b},insert(v){mode='insert';patch=v;return b},update(v){mode='update';patch=v;return b},delete(){mode='delete';return b},then(resolve){const target=table==='evidence_files'?rows:table==='audit'?audits:jobs;if(mode==='insert'){target.push({created_at:new Date().toISOString(),state:'pending',...patch});return Promise.resolve({data:null}).then(resolve)}let selected=target.filter(r=>filters.every(f=>f(r)));if(sort)selected.sort((a,b)=>String(a[sort]).localeCompare(String(b[sort])));selected=selected.slice(0,limit);if(mode==='update')selected.forEach(r=>Object.assign(r,patch));if(mode==='delete')for(const r of selected)target.splice(target.indexOf(r),1);return Promise.resolve({data:b.single?selected[0]||null:selected.map(r=>({...r}))}).then(resolve)}};return b};
const db={from:q,rpc:async(name,args={})=>{if(name==='evidence_storage_lock'){if(args.p_release){locked=false;return {data:true}}if(locked)return {data:false};locked=true;return {data:true}}if(name==='evidence_storage_usage')return {data:{used_bytes:[...objects.values()].reduce((s,n)=>s+n,0),budget_bytes:1000,auto_cleanup:true}};if(name==='evidence_cleanup_candidates')return {data:rows.filter(r=>r.state==='active'&&Date.parse(r.created_at)<Date.now()-3600000).sort((a,b)=>a.created_at.localeCompare(b.created_at)).map(r=>({...r}))};throw Error(name)},storage:{from:()=>({remove:async paths=>{events.push(...paths);if(failDelete)return {error:Error('temporary')};paths.forEach(p=>objects.delete(p));return {data:[]}},upload:async(p,f)=>{objects.set(p,f.size);return {data:{path:p}}},download:async()=>({data:new Blob(['proof'],{type:'image/png'})})})}};
function add(path,size,days=2){rows.push({path,name:path,size,mime_type:'image/png',created_at:new Date(Date.now()-days*86400000).toISOString(),state:'active'});objects.set(path,size)}
(async()=>{
add('oldest',150,4);add('middle',100,3);add('newest',700,2);let r=await api.maintainEvidence(db);assert.deepEqual(events,['oldest']);assert.equal(r.used_bytes,800);assert.equal(rows[0].state,'deleted');assert.equal(audits.length,1);assert.equal(locked,false);
await assert.rejects(()=>api.downloadEvidence(db,'sb:oldest'),/ถูกลบ/);
reset();add('queued',20);jobs.push({id:'job',kind:'drive',target:'sb:queued'});failDelete=true;await assert.rejects(()=>api.maintainEvidence(db),/temporary/);assert.equal(rows[0].state,'deleting');assert.equal(objects.size,1);assert.equal(jobs.length,1);failDelete=false;await api.maintainEvidence(db);assert.equal(objects.size,0);assert.equal(jobs.length,0);assert.equal(audits.length,1);
reset();locked=true;await assert.rejects(()=>api.uploadEvidence(db,new File(['x'],'x',{type:'image/png'}),'x'),/กำลังจัดการ/);assert.equal(objects.size,0);
reset();const id=await api.uploadEvidence(db,new File(['x'],'x',{type:'image/png'}),'slip');assert.match(id,/^sb:/);assert.equal(rows[0].state,'active');assert.equal((await api.downloadEvidence(db,id)).headers.get('Content-Type'),'image/png');await api.deleteEvidenceByAdmin(db,id.slice(3),'admin');assert.equal(objects.size,0);assert.match(rows[0].delete_reason,/แอดมิน/);assert.equal(locked,false);
console.log('Storage oldest-first 90→80%, queue deletion, retry after API failure, tombstones, concurrency lock, upload/download and admin deletion passed');
})().catch(e=>{console.error(e);process.exitCode=1});
