const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const root=require('node:path').resolve(__dirname,'..');
const dom=new JSDOM('<div id="app"></div><dialog id="dialog"></dialog><div id="toast"></div>',{url:'https://example.test',runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window,ctx=dom.getInternalVMContext();w.FINANCE_CONFIG={mode:'demo'};w.scrollTo=()=>{};
w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.URL.createObjectURL=()=> 'blob:test';w.URL.revokeObjectURL=()=>{};
let network=async()=>({ok:true,json:async()=>({ok:true})});w.fetch=(...args)=>network(...args);
const scriptNames=[...fs.readFileSync(root+'/web/index.html','utf8').matchAll(/<script src="\.\/([^?\"]+)(?:\?[^\"]*)?" defer>/g)].map(m=>m[1]).filter(n=>!['boot.js','config.js'].includes(n));
for(const file of scriptNames)vm.runInContext(fs.readFileSync(root+'/web/'+file,'utf8'),ctx);
const run=s=>vm.runInContext(s,ctx),tick=()=>new Promise(r=>setImmediate(r));
(async()=>{
 run("demoLogin('member');nav('individual-bills')");assert.equal(w.document.querySelector('[data-individual-add]'),null,'members cannot manage bills');run("assignIndividualModal()");assert.equal(w.document.querySelector('#member-assign'),null);
 run("demoLogin('admin');openIndividualBills('u1')");assert.equal(w.document.querySelectorAll('.individual-bill').length,3);assert.match(w.document.querySelector('.individual-person').textContent,/ชวิน/);
 const input=w.document.getElementById('individual-query');input.value='ต้อนรับ';input.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(w.document.querySelectorAll('.individual-bill').length,1);assert.equal(w.document.getElementById('individual-query'),input,'filter keeps its input node');
 run("openIndividualBills('u1');editRecord('charge','c1')");const f=w.document.querySelector('#record-edit');f.elements.amount.value='175.50';f.elements.reason.value='ปรับเฉพาะบุคคล';f.requestSubmit();await tick();assert.equal(run("db.charges.find(c=>c.id==='c1').amount"),175.5);assert.equal(run("db.charges.find(c=>c.id==='c4').amount"),200,'other member unchanged');assert.equal(run("db.rounds.find(r=>r.id==='r1').amount"),200,'bill default unchanged');
 run("editRecord('charge','c3')");assert.equal(w.document.querySelector('#record-edit'),null,'paid charge is locked');run("document.getElementById('dialog').close();db.rounds.push({id:'r4',title:'ทดสอบ',amount:40,due_date:'2026-12-31'});assignIndividualModal()");
 assert.equal(w.document.querySelector('#member-assign').dataset.id,'u1');const assign=w.document.getElementById('member-assign');assign.elements.round_id.value='r4';assign.requestSubmit();await tick();assert.equal(run("db.charges.filter(c=>c.round_id==='r4'&&c.profile_id==='u1').length"),1);assert.equal(run("db.charges.filter(c=>c.round_id==='r4'&&c.profile_id==='u2').length"),0);
 run("openIndividualBills('u1');deletionModal('charge',['c1'])");const deletion=w.document.getElementById('record-delete');deletion.elements.reason.value='ยกเลิกเฉพาะคน';deletion.requestSubmit();await tick();assert.equal(run("db.charges.some(c=>c.id==='c1')"),false);assert.equal(run("db.charges.some(c=>c.id==='c4')"),true);assert.equal(run("db.trash.charge[0].id"),'c1');
 assert.match(run("dateTime('2026-10-04T18:05:00Z')"),/01:05/);assert.ok(!run("dateTime('2026-10-05')").includes('00:00'),'date-only values never invent times');
 run("db.payments[0].reviewed_at='2026-10-04T18:05:00Z';individualHistory('c3')");assert.match(w.document.getElementById('dialog').textContent,/ตรวจสอบ.*01:05/);assert.ok(w.document.querySelector('.detail-card svg'));run("document.getElementById('dialog').close();nav('dashboard');cfg.mode='live';ensureLiveSession=async()=>{};token='test'");
 let release;network=()=>new Promise(r=>release=r);
 const quiet=run("api('bootstrap')");await tick();assert.equal(run('busyJobs.size'),0,'bootstrap does not show loading');release({ok:true,json:async()=>({ok:true})});await quiet;
 const write=run("api('edit-record',{})");await tick();assert.equal(run('busyJobs.size'),1,'writes keep progress');release({ok:true,json:async()=>({ok:true})});await write;
 const auth=run("fetch('https://example.test/auth/v1/token?grant_type=refresh_token')");await tick();assert.equal(run('busyJobs.size'),0,'refresh token stays silent');release({ok:true});await auth;
 let calls=0;const snapshot=()=>JSON.parse(run("JSON.stringify({data:db,profile:user})"));
 network=async()=>{calls++;return {ok:true,json:async()=>snapshot()}};
 const before=w.document.querySelector('main');await run('refreshInBackground()');assert.equal(w.document.querySelector('main'),before,'unchanged data does not rebuild screen');assert.equal(calls,1);
 network=()=>new Promise(r=>release=r);const inFlight=run('refreshInBackground()');await tick();await run('refreshInBackground()');run("modal('กำลังแก้ไข','<input id=unsaved value=keep>')");const changed=snapshot();changed.data.settings={siteName:'changed'};release({ok:true,json:async()=>changed});await inFlight;assert.equal(w.document.getElementById('unsaved').value,'keep','background response preserves newly opened form');assert.equal(w.document.querySelector('main'),before);
 run("document.getElementById('dialog').close()");network=async()=>({ok:true,json:async()=>changed});await run('refreshInBackground()');assert.equal(run('db.settings.siteName'),'changed');assert.notEqual(w.document.querySelector('main'),before,'new data updates quietly');assert.equal(run('busyJobs.size'),0);
 console.log('Individual bill permissions, scoped edits/additions/deletion, paid locks, Thai timestamps, quiet reads, concurrent refresh and form preservation passed');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>w.close());
