const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
// State selection uses Thai calendar days, actual balances and current payment state.
const source=fs.readFileSync('web/material-expressive.js','utf8');
const stateContext={Intl,Date,Number,String,user:{id:'me',role:'member'},db:{charges:[],payments:[],rounds:[]},money:n=>Number(n).toFixed(2)};stateContext.round=id=>stateContext.db.rounds.find(r=>r.id===id)||{};stateContext.balance=c=>c.balance;stateContext.hasPending=c=>stateContext.db.payments.some(p=>p.charge_id===c.id&&['pending','review'].includes(p.status));vm.createContext(stateContext);vm.runInContext(source.split('let materialPaused=')[0],stateContext);const at=new Date('2026-10-10T17:00:00Z');
function reset(){stateContext.user={id:'me',role:'member'};stateContext.db={charges:[{id:'mine',profile_id:'me',round_id:'round',balance:300}],payments:[],rounds:[{id:'round',title:'Test',due_date:'2026-10-10'}]}}
const state=()=>stateContext.materialBillState(at);reset();assert.equal(state().mood,'overdue');stateContext.db.payments.push({charge_id:'mine',profile_id:'me',status:'review'});assert.equal(state().mood,'review');assert.equal(state().overdue.length,0);reset();stateContext.db.rounds[0].due_date='2026-10-11';assert.equal(state().mood,'soon');stateContext.db.rounds[0].due_date='2026-10-13';assert.equal(state().mood,'open');stateContext.db.payments=[{charge_id:'mine',profile_id:'me',status:'rejected',created_at:'2026-10-10'}];assert.equal(state().mood,'rejected');stateContext.db.payments.push({charge_id:'mine',profile_id:'me',status:'approved',created_at:'2026-10-11'});assert.equal(state().mood,'open','old rejected slips must not override newer approval');stateContext.db.charges[0].balance=0;assert.equal(state().mood,'paid');reset();stateContext.db.rounds[0].archived=true;assert.equal(state().mood,'calm');reset();stateContext.db.charges[0].profile_id='other';assert.equal(state().overdue.length,0);assert.equal(state().mood,'calm');stateContext.user.role='admin';stateContext.db.payments.push({charge_id:'mine',profile_id:'other',status:'review'});assert.equal(state().destination,'review');
// Load the actual page extension chain to catch integration and handler conflicts.
const html=fs.readFileSync('web/index.html','utf8'),errors=[];
const dom=new JSDOM(html,{url:'https://finance.test',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window,c=dom.getInternalVMContext(),run=s=>vm.runInContext(s,c);const observers=[],OriginalObserver=w.MutationObserver;w.MutationObserver=class extends OriginalObserver{constructor(callback){super(callback);observers.push(this)}};w.FINANCE_CONFIG={mode:'demo'};w.matchMedia=()=>({matches:false,addEventListener(){},removeEventListener(){}});w.scrollTo=()=>{};w.Element.prototype.scrollIntoView=()=>{};w.Element.prototype.animate=()=>{};w.confirm=()=>true;w.fetch=async()=>{throw Error('Unexpected network call')};w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'))};w.addEventListener('error',e=>errors.push(e.message));
for(const tag of w.document.querySelectorAll('script[src]')){const name=tag.getAttribute('src').split('?')[0].replace('./','');if(name==='config.js')continue;run(fs.readFileSync('web/'+name,'utf8'))}
const click=s=>{assert(w.document.querySelector(s),s);w.document.querySelector(s).click()};
(async()=>{await new Promise(r=>setTimeout(r,30));for(const role of ['member','admin']){run(`demoLogin('${role}')`);for(const page of role==='admin'?['dashboard','rounds','review','members','fund','reports','notifications','audit','settings','profile','individual-bills','trash']:['dashboard','bills','history','fund','notifications','profile']){run(`nav('${page}')`);assert.equal(w.document.querySelectorAll('#material-profile-menu').length,1);assert(w.document.querySelector('main'));}run("nav('dashboard')");assert.equal(w.document.querySelectorAll('.meddy-hero').length,1);assert.equal(w.document.querySelectorAll('.clay-sculpture').length,0);click('[data-material-profile-toggle]');assert.equal(w.document.querySelector('#material-profile-menu').hidden,false);run('render()');assert.equal(w.document.querySelector('#material-profile-menu').hidden,false,'refresh preserves menu');click('[data-material-profile=password]');assert(w.document.querySelector('#password-form'),'real password form opens');w.document.querySelector('#dialog').close();run("nav('dashboard')");click('[data-material-profile-toggle]');click('[data-material-profile=line]');assert.equal(run('view'),'profile');run("nav('dashboard')");click('[data-meddy-go]');assert(['bills','review','history','rounds','individual-bills'].includes(run('view')));w.document.querySelector('#dialog').close();}
run("demoLogin('member');db.charges=[{id:'target',profile_id:user.id,round_id:'r1',amount:320}];db.payments=[];db.rounds.find(r=>r.id==='r1').due_date='2020-01-01';db.rounds.find(r=>r.id==='r1').archived=false;nav('dashboard')");assert(w.document.querySelector('.meddy-overdue[role=status]'));click('[data-meddy-dismiss]');assert(!w.document.querySelector('.meddy-overdue[role=status]'));assert(w.document.querySelector('.meddy-hero'),'dismissing the alert preserves the mascot');run('render()');assert(!w.document.querySelector('.meddy-overdue[role=status]'),'dismissal survives quiet refresh');click('[data-meddy-go]');assert(w.document.querySelector('#dialog').open,'CTA opens the matching real bill');w.document.querySelector('#dialog').close();run("nav('dashboard')");click('[data-material-profile-toggle]');w.document.body.click();assert(w.document.querySelector('#material-profile-menu').hidden);click('[data-material-profile-toggle]');w.document.querySelector('[data-material-profile-toggle]').dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert(w.document.querySelector('#material-profile-menu').hidden);await new Promise(r=>setTimeout(r,400));assert.deepEqual(errors,[]);observers.forEach(o=>o.disconnect());w.close();console.log('PASS: Bangkok status selection, pending/archived/privacy guards, 18 real views, profile menu/password/LINE, quiet refresh, overdue dismissal and matching-bill CTA')})().catch(e=>{console.error(e);w.close();process.exitCode=1});
