const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path'),{JSDOM}=require('jsdom');
const root=path.resolve(__dirname,'..'),dom=new JSDOM('<div id="app"></div><dialog id="dialog"></dialog><div id="toast"></div>',{url:'https://example.test',runScripts:'outside-only'}),w=dom.window,ctx=dom.getInternalVMContext();
w.FINANCE_CONFIG={mode:'demo',supabaseUrl:'https://test',supabaseAnonKey:'public'};w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.URL.createObjectURL=()=> 'blob:test';w.URL.revokeObjectURL=()=>{};
for(const name of ['app.js','management.js','records.js','session-history.js'])vm.runInContext(fs.readFileSync(root+'/web/'+name,'utf8'),ctx);
const run=s=>vm.runInContext(s,ctx);
(async()=>{
run("demoLogin('member');nav('profile')");assert.equal(w.document.querySelector('#self-profile'),null);assert.ok(w.document.querySelector('.mobile-brand[data-view=dashboard] img'));w.document.querySelector('.mobile-brand').click();assert.equal(run('view'),'dashboard');
run("db.payments.push({...db.payments.find(p=>p.profile_id===user.id),id:'latest-test',created_at:'2030-01-01T00:00:00Z',drive_file_id:'private'});nav('history')");const total=run('db.payments.filter(p=>p.profile_id===user.id).length');assert.ok(w.document.querySelectorAll('tbody tr').length<total);assert.ok(w.document.querySelector('[data-history-proof=latest-test]'));assert.equal(run('db.payments.filter(p=>p.profile_id===user.id).length'),total);w.document.querySelector('[data-history-proof=latest-test]').click();await new Promise(r=>setImmediate(r));assert.ok(w.document.querySelector('#dialog img[data-proof-id=latest-test]'));
run("setLoginSession({access_token:'test-access',refresh_token:'test-refresh',expires_at:Math.floor(Date.now()/1000)+3600},true)");assert.ok(w.localStorage.getItem('finance-medtech-session-v1'));assert.ok(!w.localStorage.getItem('finance-medtech-session-v1').includes('password'));
run("setLoginSession({access_token:'test-access',refresh_token:'test-refresh',expires_at:Math.floor(Date.now()/1000)+3600},false)");assert.equal(w.localStorage.getItem('finance-medtech-session-v1'),null);assert.ok(w.sessionStorage.getItem('finance-medtech-session-v1'));
let calls=0;w.fetch=async()=>{calls++;return {ok:true,json:async()=>({access_token:'rotated',refresh_token:'rotated-refresh',expires_at:Math.floor(Date.now()/1000)+3600})}};run("cfg.mode='live';loginSession.expires_at=0");await run('Promise.all([ensureLiveSession(),ensureLiveSession()])');assert.equal(calls,1);assert.equal(run('token'),'rotated');await run('logoutSession()');assert.equal(run('token'),null);assert.equal(w.sessionStorage.getItem('finance-medtech-session-v1'),null);assert.equal(w.localStorage.getItem('finance-medtech-session-v1'),null);
console.log('History grouping retains records, latest evidence, admin-only profile UI, logo home, remembered/session-only login, refresh rotation and logout passed');w.close();
})().catch(e=>{console.error(e);process.exitCode=1;w.close()});
