'use strict';
const supportLine=()=>/^https:\/\/(lin\.ee|line\.me)\//.test(cfg.lineOaUrl||'')?cfg.lineOaUrl:'https://lin.ee/7VYJbx0';
function forgotPasswordModal(){modal('ลืมรหัสผ่าน',`<p>ระบุรหัสนักศึกษาเพื่อรับลิงก์ตั้งรหัสผ่านใหม่ทาง LINE ที่เชื่อมไว้</p><form id="forgot-line-form">${inputField('student_id','รหัสนักศึกษา','','text','required pattern="[0-9]{5,20}" maxlength="20" inputmode="numeric" autocomplete="username"')}<div class="actions"><button type="submit">${icon('bell')} ส่งลิงก์ไป LINE</button></div><div class="form-error" role="status"></div></form><p class="help">ยังไม่เชื่อม LINE หรือไม่ได้รับข้อความ?</p><a class="account-support" href="${esc(supportLine())}" target="_blank" rel="noopener">ติดต่อผู้ดูแลระบบทาง LINE ↗</a>`)}
async function publicAccountRequest(data){const response=await fetch(cfg.supabaseUrl+'/functions/v1/account-access',{method:'POST',headers:{apikey:cfg.supabaseAnonKey,'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw Error(result.error||'ดำเนินการไม่สำเร็จ');return result}
document.addEventListener('click',e=>{if(e.target.closest('[data-action=forgot]')){e.preventDefault();e.stopImmediatePropagation();forgotPasswordModal()}},true);
const accessRender=render;render=function(){accessRender();if(user?.role==='admin'&&view==='members')document.querySelector('.page-head .button-group')?.insertAdjacentHTML('beforeend',`<button class="secondary" data-new-invite>${icon('plus')} ลิงก์สมัครสมาชิก</button>`)};
let demoInvites=[];
function inviteModal(){if(user?.role!=='admin')return;const expiry=new Date(Date.now()+86400000).toLocaleString('sv-SE',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).replace(' ','T');modal('สร้างลิงก์สมัครสมาชิก',`<form id="member-invite-form">${inputField('student_id','รหัสนักศึกษา','','text','required pattern="[0-9]{5,20}" maxlength="20" inputmode="numeric"')}${inputField('name_prefix','คำนำหน้า','','text','required maxlength="30" list="name-prefixes"')}<datalist id="name-prefixes"><option value="นาย"><option value="นางสาว"><option value="นาง"></datalist><div class="form-grid">${inputField('first_name','ชื่อ','','text','required maxlength="60"')}${inputField('last_name','นามสกุล','','text','required maxlength="60"')}</div>${selectField('year','ชั้นปี','1',[['1','1'],['2','2'],['3','3'],['4','4']])}${inputField('expires_at','วันและเวลาหมดอายุ (เวลาไทย)',expiry,'datetime-local','required')}<p class="help">ลิงก์ใช้ได้ครั้งเดียว อายุไม่เกิน 30 วัน ผู้สมัครตั้งเฉพาะรหัสผ่าน ข้อมูลประจำตัวใช้ตามที่ระบุไว้ข้างบน</p><div class="actions"><button type="button" class="secondary" data-list-invites>ลิงก์ที่สร้างไว้</button><button type="submit">สร้างลิงก์</button></div><div class="form-error"></div></form>`)}
async function listInvites(){if(user?.role!=='admin')return;try{const rows=cfg.mode==='live'?(await api('list-member-invites')).invites:demoInvites;modal('ลิงก์สมัครสมาชิก',rows.length?rows.map(r=>`<div class="invite-item"><strong>${esc(r.name_prefix+r.first_name+' '+r.last_name)}</strong><p>${esc(r.student_id)} · หมดอายุ ${esc(dateTime(r.expires_at))}</p><div class="actions"><span>${r.status==='used'?'สมัครแล้ว':r.status==='revoked'?'ยกเลิกแล้ว':r.status==='processing'?'กำลังสร้างบัญชี':Date.parse(r.expires_at)<=Date.now()?'หมดอายุ':'รอสมัคร'}</span>${r.status==='pending'?`<button class="danger small" data-revoke-invite="${esc(r.id)}">ยกเลิกลิงก์</button>`:''}</div></div>`).join(''):'<p class="empty">ยังไม่มีลิงก์สมัครสมาชิก</p>')}catch(err){toast(err.message)}}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-new-invite'))inviteModal();if(b.hasAttribute('data-list-invites'))listInvites();if(b.hasAttribute('data-copy-invite')){const input=document.getElementById('generated-invite-url');try{await navigator.clipboard.writeText(input.value);toast('คัดลอกลิงก์แล้ว')}catch{input.focus();input.select();toast('เลือกลิงก์ไว้แล้ว สามารถคัดลอกได้')}}if(b.dataset.revokeInvite&&user?.role==='admin'){b.disabled=true;try{if(cfg.mode==='live')await api('revoke-member-invite',{id:b.dataset.revokeInvite});else demoInvites.find(r=>r.id===b.dataset.revokeInvite).status='revoked';await listInvites()}catch(err){toast(err.message)}finally{b.disabled=false}}});
document.addEventListener('submit',async e=>{const f=e.target;if(!['forgot-line-form','member-invite-form'].includes(f.id))return;e.preventDefault();e.stopImmediatePropagation();if(f.dataset.saving)return;if(f.id==='member-invite-form'&&user?.role!=='admin')return;f.dataset.saving='true';const b=f.querySelector('[type=submit]'),original=b.innerHTML;b.disabled=true;b.textContent=f.id==='forgot-line-form'?'กำลังส่งลิงก์…':'กำลังสร้างลิงก์…';try{const data=Object.fromEntries(new FormData(f));if(f.id==='forgot-line-form'){const result=cfg.mode==='live'?await publicAccountRequest({action:'forgot',student_id:data.student_id}):{message:'โหมดทดลอง: ไม่ได้ส่ง LINE จริง หากบัญชีเชื่อม LINE ไว้ ระบบจะส่งลิงก์ตั้งรหัสให้'};f.querySelector('.form-error').textContent=result.message}else{const expires=new Date(data.expires_at+':00+07:00');if(!Number.isFinite(expires.getTime())||expires<=new Date(Date.now()+60000)||expires>new Date(Date.now()+30*86400000))throw Error('กำหนดหมดอายุหลังจากนี้อย่างน้อย 1 นาที และไม่เกิน 30 วัน');const payload={...data,expires_at:expires.toISOString()};let result;if(cfg.mode==='live')result=await api('create-member-invite',payload);else{result={id:crypto.randomUUID(),url:new URL('./register.html#token=demo',location.href).href};demoInvites.push({...payload,...result,status:'pending'})}await refresh();render();modal('สร้างลิงก์สมัครแล้ว',`<p>${esc(data.name_prefix+data.first_name+' '+data.last_name)} · ${esc(data.student_id)}</p><p class="help">หมดอายุ ${esc(dateTime(payload.expires_at))} · ใช้ได้ครั้งเดียว</p><label for="generated-invite-url">ลิงก์สำหรับส่งให้ผู้สมัคร</label><input id="generated-invite-url" value="${esc(result.url)}" readonly><div class="actions"><button data-copy-invite>คัดลอกลิงก์</button><button class="secondary" data-list-invites>ลิงก์ที่สร้างไว้</button></div>`)} }catch(err){f.querySelector('.form-error').innerHTML=`<p class="error">${esc(err.message)}</p>`}finally{b.disabled=false;b.innerHTML=original;delete f.dataset.saving}},true);
if(user)render();
