'use strict';
function billMemberFields(selected){const members=db.profiles.filter(p=>p.role==='member'&&p.active!==false);return `<fieldset class="bill-members"><legend>สมาชิกที่ต้องชำระ</legend><div class="button-group"><button type="button" class="secondary small" data-bill-select="all">เลือกทั้งหมด</button><button type="button" class="secondary small" data-bill-select="none">ล้างการเลือก</button></div>${members.length?members.map(p=>`<label><input type="checkbox" name="profile_ids" value="${esc(p.id)}" ${selected.includes(p.id)?'checked':''}><span>${esc(p.name)}<small>${esc(p.student_id)} · ปี ${esc(p.year||'—')}</small></span></label>`).join(''):'<p class="help">เพิ่มสมาชิกก่อนสร้างบิล</p>'}</fieldset>`}
function penaltyFields(r={}){return `<label class="checkbox-label"><input type="checkbox" name="penalty_enabled" ${r.penalty_enabled?'checked':''}>คิดค่าปรับเมื่อเกินกำหนด</label>${inputField('penalty_per_day','ค่าปรับต่อวัน (บาท)',r.penalty_per_day||'','number',`min="0.01" max="1000000" step="0.01" ${r.penalty_enabled?'required':'disabled'}`)}<p class="help">เริ่มวันถัดจากกำหนดชำระตามเวลาไทย หยุดเมื่อชำระครบ</p>`}
newRound=function(){modal('สร้างบิล',`<form id="bill-create">${inputField('title','ชื่อบิล','','text','required maxlength="120"')}${inputField('description','รายละเอียด','','text','maxlength="1000"')}${inputField('amount','ยอดต่อคน (บาท)','','number','required min="0.01" max="1000000" step="0.01"')}${inputField('due_date','วันครบกำหนด','','date','required')}${penaltyFields()}${billMemberFields(db.profiles.filter(p=>p.role==='member'&&p.active!==false).map(p=>p.id))}<div class="actions"><button type="button" class="secondary" data-action="close">ยกเลิก</button><button type="submit">สร้างบิล</button></div><div class="form-error"></div></form>`)};
const billsEditRecord=editRecord;editRecord=function(entity,id){if(entity!=='round')return billsEditRecord(entity,id);const r=db.rounds.find(r=>r.id===id);if(!r)return;const selected=db.charges.filter(c=>c.round_id===id&&!c.deleted_at).map(c=>c.profile_id);modal('แก้ไขบิล',recordForm('round',id,inputField('title','ชื่อบิล',r.title,'text','required maxlength="120"')+inputField('description','รายละเอียด',r.description||'','text','maxlength="1000"')+inputField('amount','ยอดต่อคน (บาท)',r.amount,'number','required min="0.01" max="1000000" step="0.01"')+inputField('due_date','วันครบกำหนด',r.due_date,'date','required')+selectField('archived','การรับชำระ',String(!!r.archived),[['false','เปิดรับชำระ'],['true','ปิดรับชำระ']])+penaltyFields(r)+billMemberFields(selected)+'<p class="help">สมาชิกที่มีการชำระหรือรายการรอตรวจแล้วจะนำออกจากบิลไม่ได้</p>'))};
const billsContent=content;content=function(){let html=billsContent();if(user?.role==='admin'&&view==='rounds'){const t=document.createElement('template');t.innerHTML=html;t.content.querySelectorAll('.round-summary').forEach((el,i)=>{const r=db.rounds[i];el.insertAdjacentHTML('afterend',`<p class="help">${r.penalty_enabled?`ค่าปรับ ฿${money(r.penalty_per_day)} ต่อวันเมื่อเกินกำหนด`:'ไม่คิดค่าปรับ'}</p>`)});html=t.innerHTML}return html};
const billsRender=render;render=function(){billsRender();if(user?.role==='admin'&&view==='trash'&&Object.values(db.trash||{}).some(rows=>rows.length))$('.page-head')?.insertAdjacentHTML('beforeend','<button class="danger small" data-empty-trash>ล้างถังขยะ</button>');document.querySelectorAll('[data-edit]').forEach(b=>{const next=b.nextElementSibling;if(next?.hasAttribute('data-delete-entity')&&!b.parentElement.classList.contains('button-group')&&!b.parentElement.classList.contains('compact-actions')){const group=document.createElement('span');group.className='compact-actions';b.before(group);group.append(b,next)}})};
document.addEventListener('change',e=>{if(e.target.name==='penalty_enabled'){const input=e.target.closest('form').querySelector('[name=penalty_per_day]');input.disabled=!e.target.checked;input.required=e.target.checked}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.billSelect){b.closest('form').querySelectorAll('[name=profile_ids]').forEach(i=>i.checked=b.dataset.billSelect==='all')}if(b.hasAttribute('data-empty-trash'))modal('ล้างถังขยะถาวร',`<p class="note">รายการทั้งหมดในถังขยะจะถูกลบถาวรและกู้คืนไม่ได้ ประวัติรับเงินจริงที่ยังใช้งานจะยังคงอยู่</p><form id="trash-purge">${inputField('confirmation','พิมพ์ ลบถาวร เพื่อยืนยัน','','text','required autocomplete="off"')}<div class="actions"><button type="button" class="secondary" data-action="close">ยกเลิก</button><button type="submit" class="danger">ล้างถังขยะถาวร</button></div><div class="form-error"></div></form>`)});
document.addEventListener('submit',async e=>{const f=e.target;if(!['bill-create','trash-purge'].includes(f.id))return;e.preventDefault();e.stopImmediatePropagation();const buttons=[...f.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{if(user.role!=='admin')throw Error('ไม่มีสิทธิ์ดำเนินการ');if(f.id==='trash-purge'){const confirmation=f.querySelector('[name=confirmation]').value;if(confirmation!=='ลบถาวร')throw Error('พิมพ์ ลบถาวร เพื่อยืนยัน');if(cfg.mode==='live')await api('purge-trash',{confirmation});else{db.trash={};audit('ล้างถังขยะถาวร')}}else{const d=Object.fromEntries(new FormData(f));d.profile_ids=[...f.querySelectorAll('[name=profile_ids]:checked')].map(i=>i.value);d.penalty_enabled=f.querySelector('[name=penalty_enabled]').checked;d.penalty_per_day=d.penalty_enabled?Number(d.penalty_per_day):0;d.amount=Number(d.amount);if(!d.profile_ids.length)throw Error('เลือกสมาชิกอย่างน้อยหนึ่งคน');if(d.penalty_enabled&&!(d.penalty_per_day>0))throw Error('ระบุค่าปรับต่อวัน');if(cfg.mode==='live')await api('new-round',d);else{const r={...d,id:crypto.randomUUID(),created_at:new Date().toISOString()};db.rounds.push(r);d.profile_ids.forEach(id=>db.charges.push({id:crypto.randomUUID(),profile_id:id,round_id:r.id,amount:d.amount}));audit('สร้างบิล '+d.title)}}await refresh();$('#dialog').close();render();toast(f.id==='bill-create'?'สร้างบิลแล้ว':'ล้างถังขยะแล้ว')}catch(err){f.querySelector('.form-error').innerHTML=`<p class="error" role="alert">${esc(err.message)}</p>`}finally{buttons.forEach(b=>b.disabled=false)}},true);
// Recalculate the displayed daily fee when the page stays open across midnight.
function updateDisplayedFees(){if(!db)return;const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());for(const c of db.charges){const r=round(c.round_id);if(!r.penalty_enabled){c.fee_amount=0;continue}if(c.fee_settled!=null&&paid(c)>=Number(c.amount)+Number(c.fee_settled)){c.fee_amount=Number(c.fee_settled);continue}if(hasPending(c))continue;const days=Math.max(0,Math.round((Date.parse(today)-Date.parse(r.due_date))/86400000));c.fee_amount=Math.round(days*Number(r.penalty_per_day)*100)/100}}
const feeRender=render;render=function(){updateDisplayedFees();feeRender()};

const feePayModal=payModal;payModal=function(id){updateDisplayedFees();return feePayModal(id)};
