'use strict';
function paymentWindowOpen(at=new Date()){const p=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Bangkok',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(at).split(':').map(Number),m=p[0]*60+p[1];return m>=60&&m<1430}
function paymentPause(){modal('พักรับชำระเงิน',`<div class="payment-celebration pause"><span class="payment-check">${icon('history')}</span><h3>กลับมาชำระได้เวลา 01:00 น.</h3><p>พักรับชำระทุกวัน 23:50–01:00 น. ตามเวลาไทย</p><button data-action="close">เข้าใจแล้ว</button></div>`)}
const timedPayModal=payModal;payModal=function(id){if(!paymentWindowOpen())return paymentPause();timedPayModal(id);const f=document.getElementById('pay-form');if(f)f.insertAdjacentHTML('afterbegin','<p class="help payment-hours">ปิดรับชำระชั่วคราวเวลา 23:50–01:00 น. (เวลาไทย)</p>')};
document.addEventListener('submit',e=>{if(e.target.id==='pay-form'&&!paymentWindowOpen()){e.preventDefault();e.stopImmediatePropagation();paymentPause()}},true);
setInterval(()=>{if(document.getElementById('pay-form')&&document.getElementById('dialog').open&&!paymentWindowOpen()&&!busyJobs.size)paymentPause()},15000);
const communicationsContent=content;content=function(){let html=communicationsContent();if(view==='dashboard'){const rows=(db.announcements||[]).filter(n=>!n.dismissed_at);if(rows.length)html=`<section class="dashboard-announcements" aria-label="ประกาศ"><div class="announcement-tabs" role="tablist">${rows.map((n,i)=>`<button role="tab" aria-selected="${i===0}" data-announcement-tab="${esc(n.id)}">${icon('bell')} ${esc(n.title)}</button>`).join('')}</div>${rows.map((n,i)=>`<article class="announcement-banner" data-announcement-pane="${esc(n.id)}" ${i?'hidden':''}><div><span class="eyebrow">ประกาศ</span><h3>${esc(n.title)}</h3><p>${esc(n.body)}</p></div><button class="ghost small" data-dismiss-announcement="${esc(n.id)}" aria-label="ปิดประกาศ">✕</button></article>`).join('')}</section>`+html}return html};
const seenPaymentAlerts=new Set();let alertQueued=false;
function showPaymentSuccess(){if(!user||document.getElementById('dialog').open)return;const n=db.notifications.find(n=>n.profile_id===user.id&&n.message_kind==='payment_success'&&!n.seen_at&&!seenPaymentAlerts.has(n.id));if(!n)return;seenPaymentAlerts.add(n.id);n.seen_at=new Date().toISOString();modal('ชำระเงินสำเร็จ',`<div class="payment-celebration"><span class="payment-check"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="m5 12 4 4L19 6"/></svg></span><h2>ชำระเงินสำเร็จ</h2><p>${esc(n.body.replace(/^finance MEDTECH\s*\n?/i,''))}</p><button data-action="close">เรียบร้อย</button></div>`);if(cfg.mode==='live')api('read-notification',{id:n.id}).catch(()=>{})}
const communicationsRender=render;render=function(){communicationsRender();if(user&&!alertQueued){alertQueued=true;queueMicrotask(()=>{alertQueued=false;showPaymentSuccess()})}};
document.getElementById('dialog').addEventListener('close',()=>queueMicrotask(showPaymentSuccess));
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||!user)return;if(b.hasAttribute('data-web-announcement')&&user.role==='admin')return composeMessage('announcement',true);if(b.dataset.announcementTab){document.querySelectorAll('[data-announcement-pane]').forEach(p=>p.hidden=p.dataset.announcementPane!==b.dataset.announcementTab);document.querySelectorAll('[data-announcement-tab]').forEach(t=>t.setAttribute('aria-selected',String(t===b)))}if(b.dataset.dismissAnnouncement){b.disabled=true;try{if(cfg.mode==='live')await api('dismiss-announcement',{id:b.dataset.dismissAnnouncement});const n=db.announcements.find(x=>x.id===b.dataset.dismissAnnouncement);if(n)n.dismissed_at=new Date().toISOString();render()}catch(err){toast(err.message);b.disabled=false}}if(b.dataset.deleteAnnouncement&&user.role==='admin')modal('ลบประกาศในเว็บ',`<p>นำประกาศนี้ออกจากเว็บของผู้รับทุกคน?</p><form id="delete-web-announcement" data-id="${esc(b.dataset.deleteAnnouncement)}"><div class="actions"><button type="button" class="secondary" data-action="close">ยกเลิก</button><button type="submit" class="danger">ลบประกาศ</button></div><div class="form-error"></div></form>`)});
document.addEventListener('submit',async e=>{const f=e.target;if(f.id!=='delete-web-announcement')return;e.preventDefault();e.stopImmediatePropagation();const b=f.querySelector('[type=submit]');b.disabled=true;try{if(user.role!=='admin')throw Error('ไม่มีสิทธิ์');if(cfg.mode==='live')await api('delete-announcement',{id:f.dataset.id});db.announcements=db.announcements.filter(n=>n.id!==f.dataset.id);document.getElementById('dialog').close();render();toast('ลบประกาศแล้ว')}catch(err){f.querySelector('.form-error').textContent=err.message}finally{b.disabled=false}},true);
let backgroundRefreshRunning=false;
async function refreshInBackground(){
 if(backgroundRefreshRunning||cfg.mode!=='live'||!user||document.hidden||document.getElementById('dialog').open||busyJobs.size)return;
 backgroundRefreshRunning=true;const scope=user.id+'|'+user.role,screen=view;
 try{
  const result=await api('bootstrap');
  if(!user||scope!==user.id+'|'+user.role||view!==screen||document.hidden||document.getElementById('dialog').open||busyJobs.size||document.activeElement?.matches('input,select,textarea,[contenteditable=true]'))return;
  const changed=JSON.stringify(db)!==JSON.stringify(result.data)||JSON.stringify(user)!==JSON.stringify(result.profile);
  if(!changed)return;
  db=result.data;user=result.profile;for(const key of settingKeys)if(typeof db.settings?.[key]==='string')cfg[key]=db.settings[key];
  const scroll=window.scrollY,activeAnnouncement=document.querySelector('[data-announcement-tab][aria-selected=true]')?.dataset.announcementTab;
  const detailKey=el=>el.classList.contains('completed-bills')?'completed-bills':el.closest('.activity-card')?.textContent;
  const openDetails=new Set([...document.querySelectorAll('main .completed-bills[open],main .activity-changes[open]')].map(detailKey));
  render();
  document.querySelectorAll('main .completed-bills,main .activity-changes').forEach(el=>el.open=openDetails.has(detailKey(el)));
  if(activeAnnouncement&&[...document.querySelectorAll('[data-announcement-tab]')].some(el=>el.dataset.announcementTab===activeAnnouncement)){
   document.querySelectorAll('[data-announcement-tab]').forEach(el=>el.setAttribute('aria-selected',String(el.dataset.announcementTab===activeAnnouncement)));
   document.querySelectorAll('[data-announcement-pane]').forEach(el=>el.hidden=el.dataset.announcementPane!==activeAnnouncement);
  }
  document.querySelectorAll('main .mobile-record-table tr,main .clay-bill-body,main .record-original-content,main .individual-bill-body').forEach(el=>el.style.animation='none');
  window.scrollTo({top:scroll,behavior:'instant'});
 }catch{/* Background sync retries on the next interval; user actions still report errors. */}
 finally{backgroundRefreshRunning=false}
}
setInterval(refreshInBackground,60000);
operationLabels['publish-announcement']='กำลังเผยแพร่ประกาศ';operationLabels['dismiss-announcement']='กำลังปิดประกาศ';operationLabels['read-notification']='กำลังบันทึกการอ่าน';if(user)render();

let announcementTimer=null,announcementActive='',announcementPaused=false;
function selectAnnouncement(id){const panes=[...document.querySelectorAll('[data-announcement-pane]')];if(!panes.length)return;announcementActive=panes.some(p=>p.dataset.announcementPane===id)?id:panes[0].dataset.announcementPane;panes.forEach(p=>p.hidden=p.dataset.announcementPane!==announcementActive);document.querySelectorAll('[data-announcement-tab]').forEach(t=>t.setAttribute('aria-selected',String(t.dataset.announcementTab===announcementActive)));const count=document.querySelector('[data-announcement-count]');if(count)count.textContent=(panes.findIndex(p=>!p.hidden)+1)+' / '+panes.length;}
function moveAnnouncement(step){const panes=[...document.querySelectorAll('[data-announcement-pane]')];if(panes.length<2)return;const current=panes.findIndex(p=>!p.hidden);selectAnnouncement(panes[(current+step+panes.length)%panes.length].dataset.announcementPane)}
const carouselRender=render;render=function(){carouselRender();clearInterval(announcementTimer);const section=document.querySelector('.dashboard-announcements');if(!section)return;const panes=section.querySelectorAll('[data-announcement-pane]');selectAnnouncement(announcementActive);if(panes.length<2)return;section.insertAdjacentHTML('beforeend',`<div class="announcement-controls"><button class="ghost small" data-announcement-step="-1" aria-label="ประกาศก่อนหน้า">‹</button><span data-announcement-count></span><button class="ghost small" data-announcement-step="1" aria-label="ประกาศถัดไป">›</button><button class="ghost small" data-announcement-pause aria-label="หยุดเลื่อนอัตโนมัติ">${announcementPaused?'เล่นอัตโนมัติ':'หยุดอัตโนมัติ'}</button></div>`);selectAnnouncement(announcementActive);let start=null;section.addEventListener('touchstart',e=>{start={x:e.touches[0].clientX,y:e.touches[0].clientY}},{passive:true});section.addEventListener('touchend',e=>{if(!start)return;const dx=e.changedTouches[0].clientX-start.x,dy=e.changedTouches[0].clientY-start.y;if(Math.abs(dx)>50&&Math.abs(dx)>Math.abs(dy)){announcementPaused=true;moveAnnouncement(dx<0?1:-1);section.querySelector('[data-announcement-pause]').textContent='เล่นอัตโนมัติ'}start=null},{passive:true});announcementTimer=setInterval(()=>{if(!announcementPaused&&!document.hidden&&!document.querySelector('#dialog[open]')&&!section.matches(':hover')&&!section.contains(document.activeElement)&&!window.matchMedia?.('(prefers-reduced-motion: reduce)').matches)moveAnnouncement(1)},6500)};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.announcementStep){announcementPaused=true;moveAnnouncement(Number(b.dataset.announcementStep))}if(b.dataset.announcementTab){announcementPaused=true;selectAnnouncement(b.dataset.announcementTab)}if(b.hasAttribute('data-announcement-pause'))announcementPaused=!announcementPaused;const pause=document.querySelector('[data-announcement-pause]');if(pause){pause.textContent=announcementPaused?'เล่นอัตโนมัติ':'หยุดอัตโนมัติ';pause.setAttribute('aria-label',pause.textContent)}});
