'use strict';
Object.assign(icons,{folder:'<path d="M3 7V5a2 2 0 0 1 2-2h5l2 3h7a2 2 0 0 1 2 2v11H3Z"/>',save:'<path d="M4 3h13l3 3v15H4Z"/><path d="M8 3v6h8V3M8 21v-8h8v8"/>',refresh:'<path d="M20 7a9 9 0 1 0 1 8M20 3v5h-5"/>'});
function storageReplacementOptions(){const options=[];for(const p of db.payments||[]){const member=(db.profiles||[]).find(x=>x.id===p.profile_id);options.push({value:'payment|'+p.id,label:'สลิป · '+(member?.name||p.member_snapshot?.name||p.id)+' · '+Number(p.amount).toLocaleString('th-TH')+' บาท · '+new Date(p.created_at).toLocaleDateString('th-TH')})}for(const [kind,rows] of [['income',db.incomes||[]],['expense',db.expenses||[]]])for(const r of rows)for(const receipt of [false,true])options.push({value:kind+(receipt?'-receipt':'')+'|'+r.id,label:(kind==='income'?'รายรับ':'รายจ่าย')+' · '+r.title+' · '+(receipt?'ใบเสร็จ':'หลักฐาน')});return options.map(o=>`<option value="${esc(o.value)}">${esc(o.label)}</option>`).join('')}
const driveStatusContent=content;
content=function(){const html=driveStatusContent();if(user?.role!=='admin'||view!=='settings')return html;return html+panel('พื้นที่เก็บหลักฐาน',`<div class="panel-body"><p>สลิปและใบเสร็จใหม่เก็บใน Supabase Storage แบบส่วนตัว</p><button type="button" class="secondary" data-storage-open>${icon('folder')} จัดการพื้นที่และดูไฟล์</button><p class="help">รูปจะถูกลบเมื่อลบรายการถาวร · แอดมินลบรูปหรืออัปโหลดหลักฐานแทนได้</p></div>`)};
const storageBytes=n=>Number(n)>=1073741824?(Number(n)/1073741824).toFixed(2)+' GB':(Number(n)/1048576).toFixed(2)+' MB';
let storagePage=0,storageObjectUrl=null,storageRequest=0;
function releaseStoragePreview(){if(storageObjectUrl){URL.revokeObjectURL(storageObjectUrl);storageObjectUrl=null}}
document.getElementById('dialog').addEventListener('close',()=>{storageRequest++;releaseStoragePreview()});
async function openStorage(page=0){
 if(cfg.mode!=='live'){toast('พื้นที่หลักฐานใช้งานในระบบจริง');return}
 const request=++storageRequest;releaseStoragePreview();const data=await api('storage-overview',{page});if(request!==storageRequest)return;storagePage=page;const u=data.usage,percent=Math.min(100,Number(u.used_bytes)/Number(u.budget_bytes)*100);
 modal('จัดการพื้นที่หลักฐาน',`<div class="storage-summary"><strong>${storageBytes(u.used_bytes)} / ${storageBytes(u.budget_bytes)}</strong><span>เหลือ ${storageBytes(Math.max(0,Number(u.budget_bytes)-Number(u.used_bytes)))} · ${Number(u.file_count)} ไฟล์ · ${percent.toFixed(1)}%</span><progress value="${percent}" max="100" aria-label="พื้นที่ใช้แล้ว"></progress></div><form id="evidence-storage-settings"><label>เพดานพื้นที่สำหรับเว็บ (MB)<input name="budget_mb" type="number" min="100" max="102400" required value="${Number(u.budget_bytes)/1048576}"></label><p class="help">เป็นเพดานที่เว็บกำหนด ไม่ใช่การเพิ่มโควตาแพ็กเกจ Supabase</p><label class="storage-toggle"><input name="auto_cleanup" type="checkbox" ${u.auto_cleanup?'checked':''}> ลบไฟล์เก่าสุดอัตโนมัติเมื่อพื้นที่ถึง 90% จนเหลือ 80%</label><p class="help">ตรวจทุก 10 นาทีและก่อนอัปโหลด · เว้นสลิปรอตรวจและไฟล์ใหม่ไม่ถึง 1 ชั่วโมง · ลบแล้วกู้รูปคืนไม่ได้ แต่ข้อมูลการเงินยังอยู่</p><div class="storage-actions"><button type="submit">${icon('save')} บันทึก</button><button type="button" class="secondary" data-storage-clean>${icon('refresh')} ตรวจพื้นที่ตอนนี้</button></div></form><details class="storage-replace"><summary>อัปโหลดหลักฐานให้รายการเดิม</summary><form id="storage-replace-form"><label>เลือกรายการ<select name="target" required><option value="">เลือกรายการ</option>${storageReplacementOptions()}</select></label><label>สลิป / หลักฐาน / ใบเสร็จ<input type="file" name="evidence" accept="image/jpeg,image/png,image/webp,application/pdf" required></label><p class="help">เปลี่ยนเฉพาะหลักฐาน ไม่เปลี่ยนยอดเงินหรือสถานะบิล · สลิปต้องเป็นรูปภาพ</p><button type="submit">${icon('save')} อัปโหลดแทน</button></form></details><h3>ไฟล์และประวัติการลบ</h3><div class="storage-file-list">${data.files.map(f=>`<article class="storage-file"><div><strong>${esc(f.name)}</strong><p>${esc(new Date(f.created_at).toLocaleString('th-TH',{timeZone:'Asia/Bangkok'}))} · ${storageBytes(f.size)}</p><p>${esc(f.state==='active'?'พร้อมใช้งาน':f.state==='deleted'?'ลบแล้ว':f.state==='deleting'?'รอลบซ้ำ':'กำลังอัปโหลด')}${f.delete_reason?' · '+esc(f.delete_reason):''}</p>${f.deleted_at?'<p>ลบเมื่อ '+esc(new Date(f.deleted_at).toLocaleString('th-TH',{timeZone:'Asia/Bangkok'}))+'</p>':''}</div>${f.state==='active'?`<button type="button" class="secondary" data-storage-file="${esc(f.path)}" aria-label="ดูหลักฐาน">${icon('eye')} ดู</button><button type="button" class="danger" data-storage-delete="${esc(f.path)}" aria-label="ลบรูปถาวร">${icon('trash')}</button>`:''}</article>`).join('')||'<p class="help">ยังไม่มีไฟล์ใหม่ใน Supabase</p>'}</div><div class="storage-actions"><button type="button" class="secondary" data-storage-page="${page-1}" ${page===0?'disabled':''}>ก่อนหน้า</button><span>หน้า ${page+1}</span><button type="button" class="secondary" data-storage-page="${page+1}" ${data.files.length<30?'disabled':''}>ถัดไป</button></div><div id="storage-file-preview"></div>`);
}
document.addEventListener('click',async e=>{
 const b=e.target.closest('[data-storage-open],[data-storage-page],[data-storage-clean],[data-storage-file],[data-storage-delete]');if(!b||user?.role!=='admin')return;b.disabled=true;
 try{if(b.hasAttribute('data-storage-delete')){if(!confirm('ลบรูปนี้ถาวร? กู้รูปคืนไม่ได้ แต่รายการและยอดเงินยังอยู่'))return;await api('storage-delete',{path:b.dataset.storageDelete,confirmation:'ลบรูปถาวร'});toast('ลบรูปเรียบร้อย');await openStorage(storagePage)}else if(b.hasAttribute('data-storage-open'))await openStorage();else if(b.hasAttribute('data-storage-page'))await openStorage(Number(b.dataset.storagePage));else if(b.hasAttribute('data-storage-clean')){const r=await api('storage-maintain');toast('ตรวจพื้นที่เรียบร้อย · ลบ '+r.removed+' ไฟล์ตามเกณฑ์');await openStorage(storagePage)}else{
 const request=++storageRequest;await ensureLiveSession();const res=await fetch(`${cfg.supabaseUrl}/functions/v1/finance-api?action=storage-file&id=${encodeURIComponent(b.dataset.storageFile)}`,{headers:{Authorization:`Bearer ${token}`,apikey:cfg.supabaseAnonKey}});if(!res.ok){const j=await res.json();throw Error(j.error||'เปิดหลักฐานไม่ได้')}
 const blob=await res.blob();if(request!==storageRequest)return;const box=document.getElementById('storage-file-preview');if(!box)return;releaseStoragePreview();storageObjectUrl=URL.createObjectURL(blob);box.innerHTML=blob.type==='application/pdf'?'<iframe title="ใบเสร็จ PDF" class="fund-pdf"></iframe>':'<img class="preview-image" alt="หลักฐาน">';box.firstElementChild.src=storageObjectUrl;box.scrollIntoView({behavior:'smooth',block:'nearest'});
 }}catch(err){toast(err.message)}finally{b.disabled=false}
});
document.addEventListener('submit',async e=>{if(e.target.id!=='evidence-storage-settings')return;e.preventDefault();e.stopImmediatePropagation();if(user?.role!=='admin')return;const form=e.target,b=form.querySelector('[type=submit]');b.disabled=true;try{await api('storage-settings',{budget_mb:Number(form.elements.budget_mb.value),auto_cleanup:form.elements.auto_cleanup.checked});toast('บันทึกการตั้งค่าพื้นที่แล้ว');await openStorage(storagePage)}catch(err){toast(err.message)}finally{b.disabled=false}},true);
Object.assign(operationLabels,{'storage-overview':'กำลังเปิดพื้นที่หลักฐาน','storage-settings':'กำลังบันทึกการตั้งค่า','storage-maintain':'กำลังตรวจและจัดการพื้นที่'});

document.addEventListener('submit',async e=>{if(e.target.id!=='storage-replace-form')return;e.preventDefault();e.stopImmediatePropagation();if(user?.role!=='admin')return;const form=e.target,b=form.querySelector('[type=submit]'),[kind,id]=form.elements.target.value.split('|'),file=form.elements.evidence.files[0];if(!id||!file)return;b.disabled=true;try{await api('replace-evidence',{kind,id},file);toast('อัปโหลดหลักฐานใหม่แล้ว');await openStorage(storagePage)}catch(err){toast(err.message)}finally{b.disabled=false}},true);
Object.assign(operationLabels,{'storage-delete':'กำลังลบรูป','replace-evidence':'กำลังอัปโหลดหลักฐานใหม่'});
