'use strict';
const thaiTimestamp=value=>{const d=new Date(value);return Number.isNaN(d.getTime())?'ไม่ระบุเวลา':d.toLocaleString('th-TH',{timeZone:'Asia/Bangkok',day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})};
function noticePresentation(n){
 const body=String(n.body||'').replace(/^finance MEDTECH\s*\n?/i,'').trim();
 const title=n.title&&n.title!=='finance MEDTECH'?n.title:/กรุณาแก้ไข|ไม่ผ่าน/.test(body)?'กรุณาแก้ไขหลักฐาน':/ยืนยันชำระ|ยืนยันรับเงิน/.test(body)?'ยืนยันการชำระเงินแล้ว':/ยอดค้าง/.test(body)?'แจ้งเตือนยอดค้างชำระ':'แจ้งข่าวสาร';
 const tone=/แก้ไขหลักฐาน|ไม่ผ่าน/.test(title)?'attention':/ยืนยัน/.test(title)?'success':'info';
 return {title,body,tone};
}
noticeRow=function(n){const p=noticePresentation(n),person=db.profiles.find(x=>x.id===n.profile_id),delivery={sent:'ส่ง LINE แล้ว',failed:'ส่ง LINE ไม่สำเร็จ',unlinked:'ยังไม่ได้เชื่อม LINE',pending:'กำลังส่ง LINE',in_app:'แจ้งเตือนในเว็บ'}[n.status]||'ข้อความในระบบ';return `<article class="message-card ${p.tone}"><span class="message-symbol">${icon(p.tone==='success'?'check':'bell')}</span><div class="message-content"><div class="message-heading"><h3>${esc(p.title)}</h3><span class="delivery-tag">${esc(delivery)}</span></div><p class="message-description">${esc(p.body||'เปิดรายการที่เกี่ยวข้องเพื่อตรวจสอบรายละเอียด')}</p><footer>${user.role==='admin'&&person?`<span>ถึง ${esc(person.name)} · ${esc(person.student_id)}</span>`:''}<time>${n.status==='in_app'?'ครบกำหนด '+date(n.created_at):thaiTimestamp(n.created_at)}</time></footer></div></article>`};
const originalNotices=noticeList;noticeList=function(){return [...db.notifications.filter(n=>n.profile_id===user.id||user.role==='admin'),...ownCharges().filter(c=>balance(c)>0).map(c=>({title:round(c.round_id).title,body:`ยอดที่ต้องชำระ ฿${money(balance(c))}\nครบกำหนด ${date(round(c.round_id).due_date)}`,profile_id:c.profile_id,created_at:round(c.round_id).due_date,status:'in_app'}))].sort((a,b)=>{if((a.status==='in_app')!==(b.status==='in_app'))return a.status==='in_app'?1:-1;return a.status==='in_app'?(Date.parse(a.created_at)||0)-(Date.parse(b.created_at)||0):(Date.parse(b.created_at)||0)-(Date.parse(a.created_at)||0)})};
const activityFields={title:'ชื่อรายการ',description:'รายละเอียด',name:'ชื่อสมาชิก',student_id:'รหัสนักศึกษา',year:'ชั้นปี',amount:'จำนวนเงิน',due_date:'กำหนดชำระ',penalty_enabled:'การคิดค่าปรับ',penalty_per_day:'ค่าปรับต่อวัน',penalty_max:'ค่าปรับสูงสุด',archived:'ปิดรับชำระ',active:'สถานะใช้งาน',role:'สิทธิ์ผู้ใช้',status:'สถานะรายการ',note:'หมายเหตุ',category:'หมวดหมู่',spent_on:'วันที่จ่าย',received_on:'วันที่รับ',voided:'ยกเลิกรายการ',phone:'เบอร์โทร',contact_email:'อีเมล',profile_note:'ข้อมูลเพิ่มเติม',bankName:'ธนาคาร',accountName:'ชื่อบัญชี',accountNumber:'บัญชีรับเงิน',paymentQrUrl:'QR ชำระเงิน',lineOaUrl:'LINE OA',deleted_at:'ถังขยะ'};
function activityValue(key,value){if(value==null||value==='')return 'ไม่ระบุ';if(key==='paymentQrUrl')return 'รูป QR ชำระเงิน';if(key==='deleted_at')return 'ย้ายเข้าถังขยะ';if(typeof value==='boolean')return value?'เปิด':'ปิด';if(['amount','penalty_per_day','penalty_max'].includes(key))return '฿'+money(value);if(['due_date','spent_on','received_on'].includes(key))return date(value);if(key==='role')return value==='admin'?'ผู้ดูแล':'สมาชิก';if(key==='status')return labels[value]||String(value);return String(value)}
function activityPresentation(a){const d=a.details||{},after=typeof d.after==='object'&&d.after||{},before=typeof d.before==='object'&&d.before||{},uuid=/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/ig;let title=String(a.action||'อัปเดตข้อมูล');const id=title.match(uuid)?.[0];const record=[...(db.profiles||[]),...(db.rounds||[]),...(db.expenses||[]),...(db.incomes||[])].find(x=>x.id===id);const name=after.title||after.name||before.title||before.name||record?.title||record?.name;
 title=title.replace(uuid,'').replace(/\b(round|member|expense|payment|charge|income)\b/g,k=>({round:'บิล',member:'สมาชิก',expense:'รายจ่าย',payment:'การชำระเงิน',charge:'ยอดเรียกเก็บ',income:'รายรับ'}[k])).replace(/:\s*$/,'').trim();
 const changes=Object.keys(activityFields).filter(k=>JSON.stringify(before[k])!==JSON.stringify(after[k])&&(k in before||k in after)).map(k=>({label:activityFields[k],before:activityValue(k,before[k]),after:activityValue(k,after[k])}));
 if(typeof d.before==='string'&&typeof d.after==='string')changes.push({label:'รหัสนักศึกษา',before:d.before,after:d.after});
 const description=[name,d.reason||d.note,Array.isArray(d.members)?`สมาชิก ${d.members.length} คน`:null].filter(Boolean).join(' · ');
 return {title,description,changes,tone:/ลบ|ยกเลิก|ส่งกลับ/.test(title)?'attention':/ยืนยัน|อนุมัติ|กู้คืน/.test(title)?'success':'info'};
}
function activityList(rows){if(!rows.length)return '<div class="empty">ยังไม่มีกิจกรรม เมื่อมีการเปลี่ยนแปลงจะแสดงที่นี่</div>';let lastDay='';return '<div class="activity-timeline">'+rows.map(a=>{const p=activityPresentation(a),day=date(a.created_at),group=day!==lastDay?`<h3 class="activity-day">${day}</h3>`:'';lastDay=day;return group+`<article class="activity-card ${p.tone}"><span class="message-symbol">${icon(p.tone==='success'?'check':'history')}</span><div class="message-content"><h3>${esc(p.title)}</h3>${p.description?`<p class="activity-description">${esc(p.description)}</p>`:''}<div class="activity-meta"><span>โดย ${esc(a.actor||'ระบบ')}</span><time>${thaiTimestamp(a.created_at)}</time></div>${p.changes.length?`<details class="activity-changes"><summary>ดูสิ่งที่เปลี่ยนแปลง · ${p.changes.length} รายการ</summary><div class="change-labels"><span>รายการ</span><span>ก่อนแก้ไข</span><span>หลังแก้ไข</span></div>${p.changes.map(c=>`<div class="change-row"><strong>${esc(c.label)}</strong><span>${esc(c.before)}</span><span>${esc(c.after)}</span></div>`).join('')}</details>`:''}</div></article>`}).join('')+'</div>'}
const experienceContent=content;content=function(){if(view==='audit'&&user.role==='admin')return head('ประวัติกิจกรรม','ดูว่าใครทำอะไร และเปลี่ยนข้อมูลส่วนไหน')+panel('กิจกรรมล่าสุด',activityList([...db.audit].sort((a,b)=>Date.parse(b.created_at)-Date.parse(a.created_at))));if(view==='notifications')return head('การแจ้งเตือน','รายละเอียดรายการและสถานะการส่ง LINE')+panel('ข้อความล่าสุด',`<div class="message-list">${noticeList().map(noticeRow).join('')||'<div class="empty">ยังไม่มีข้อความแจ้งเตือน</div>'}</div>`);return experienceContent()};
const experienceDashboard=adminDashboard;adminDashboard=function(){return experienceDashboard()+panel('ประวัติกิจกรรมล่าสุด',activityList([...db.audit].sort((a,b)=>Date.parse(b.created_at)-Date.parse(a.created_at)).slice(0,4)),'<button class="ghost small" data-view="audit">ดูทั้งหมด</button>')};
let lastAnimatedView=null;const experienceRender=render;render=function(){experienceRender();const key=(user?.id||'login')+':'+view;if(key!==lastAnimatedView){document.querySelector('main,.login-form')?.classList.add('page-enter');lastAnimatedView=key}};
if(user)render();
