'use strict';
const categoryName=value=>String(value||'ไม่ระบุหมวดหมู่').trim().replace(/\s+/g,' ');
function fundCategoryNames(){return [...new Map([...(db.settings?.fund_categories||[]),...db.expenses.map(r=>r.category),...(db.incomes||[]).map(r=>r.category)].filter(Boolean).map(v=>[categoryName(v).toLocaleLowerCase('th'),categoryName(v)])).values()].filter(n=>!(db.settings?.fund_categories_deleted||[]).includes(n.toLocaleLowerCase('th'))).sort((a,b)=>a.localeCompare(b,'th'))}
function groupFundRows(rows,kind,table){
 if(!rows.length)return table(rows,kind);
 const groups=new Map();for(const r of rows){const name=categoryName(r.category),key=name.toLocaleLowerCase('th');if(!groups.has(key))groups.set(key,{name,rows:[]});groups.get(key).rows.push(r)}
 return [...groups.values()].sort((a,b)=>a.name.localeCompare(b.name,'th')).map(g=>`<section class="fund-category"><header><span>${icon('document')} ${esc(g.name)} <small>${g.rows.length} รายการ</small></span><strong>฿${money(g.rows.filter(r=>!r.voided&&(r.workflow_status||'settled')==='settled').reduce((sum,r)=>sum+Number(r.amount),0))}</strong></header>${table(g.rows,kind)}</section>`).join('');
}
function collectionRows(){
 if(cfg.mode==='live')return db.fund_collections||[];
 const groups=new Map();for(const p of db.payments.filter(p=>p.status==='approved'&&!p.deleted_at)){const c=(db.references?.charges||db.charges).find(c=>c.id===p.charge_id),r=round(c?.round_id),key=r.id||'other';if(!groups.has(key))groups.set(key,{id:key,title:r.title||'บิลที่เก็บถาวร',amount:0,count:0,last_at:p.reviewed_at||p.created_at});const g=groups.get(key);g.amount+=Number(p.amount);g.count++;if((p.reviewed_at||p.created_at)>g.last_at)g.last_at=p.reviewed_at||p.created_at}return [...groups.values()];
}
const groupedContent=content;content=function(){let html=groupedContent();if(view!=='fund')return html;const rows=collectionRows();return html+`<div class="fund-ledger-section">${panel('รายรับจากการเก็บเงิน',rows.length?`<div class="table-wrap"><table><thead><tr><th>รายการบิล</th><th>จำนวนรายการรับเงิน</th><th>รับล่าสุด</th><th>ยอดรับรวม</th><th>รายละเอียด</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.title)}</td><td>${r.count} รายการ</td><td>${esc(dateTime(r.last_at))}</td><td><div class="ledger-amount-status"><strong>฿${money(r.amount)}</strong><span class="badge approved">รับเงินแล้ว</span></div></td><td><button class="secondary small" data-collection-id="${esc(r.id)}">${icon('eye')} ดูรายละเอียด</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">ยังไม่มีรายรับจากบิลที่ยืนยันแล้ว</div>')}</div>`};
const groupedForm=fundRecordForm;fundRecordForm=function(...args){groupedForm(...args);const input=document.querySelector('#fund-ledger-form [name=category]');if(!input)return;const current=categoryName(input.value),names=fundCategoryNames();if(!names.includes(current)&&(args[1]||!(db.settings?.fund_categories_deleted||[]).includes(current.toLocaleLowerCase('th'))))names.push(current);input.outerHTML=`<div class="category-picker"><select id="edit-category" name="category" required>${names.map(n=>`<option value="${esc(n)}" ${n===current?'selected':''}>${esc(n)}</option>`).join('')}</select><button type="button" class="secondary small" data-inline-category>${icon('plus')} เพิ่มหมวดหมู่</button><button type="button" class="danger small" data-delete-category aria-label="ลบหมวดหมู่ที่เลือก">${icon('trash')}</button></div><div id="category-delete-confirm" hidden class="category-delete-confirm"><p>ลบหมวดหมู่นี้ออกจากตัวเลือก? รายการรายรับ–รายจ่ายเดิมยังอยู่</p><button type="button" class="danger small" data-confirm-delete-category>ยืนยันลบหมวดหมู่</button><button type="button" class="secondary small" data-cancel-delete-category>ยกเลิก</button><p role="status" id="delete-category-status"></p></div><div id="inline-category-editor" hidden><label for="inline-category-name">ชื่อหมวดหมู่ใหม่</label><div class="category-picker"><input id="inline-category-name" maxlength="100" placeholder="พิมพ์ชื่อหมวดหมู่"><button type="button" class="secondary small" data-save-inline-category>เพิ่ม</button></div><p id="inline-category-status" class="help" role="status"></p></div>`};
document.addEventListener('click',async e=>{const b=e.target.closest('[data-inline-category],[data-save-inline-category]');if(!b||user?.role!=='admin')return;const editor=document.getElementById('inline-category-editor');if(b.hasAttribute('data-inline-category')){editor.hidden=!editor.hidden;if(!editor.hidden)document.getElementById('inline-category-name').focus();return}const raw=document.getElementById('inline-category-name').value.trim(),message=document.getElementById('inline-category-status');if(!raw){message.textContent='กรุณาระบุชื่อหมวดหมู่';return}const name=categoryName(raw);b.disabled=true;try{if(cfg.mode==='live')await api('add-fund-category',{name});db.settings??={};db.settings.fund_categories_deleted=(db.settings.fund_categories_deleted||[]).filter(n=>n!==name.toLocaleLowerCase('th'));db.settings.fund_categories??=[];if(!db.settings.fund_categories.includes(name))db.settings.fund_categories.push(name);const select=document.getElementById('edit-category');let option=[...select.options].find(o=>o.value.toLocaleLowerCase('th')===name.toLocaleLowerCase('th'));if(!option){option=new Option(name,name);select.add(option)}select.value=option.value;editor.hidden=true;document.getElementById('inline-category-name').value='';message.textContent=''}catch(err){message.textContent=err.message}finally{b.disabled=false}});
function lineDestinationModal(id){if(user?.role!=='admin')return;const p=db.profiles.find(p=>p.id===id);if(!p)return;modal('เปลี่ยน LINE ปลายทาง',`<p>${esc(p.name)} · ${esc(p.student_id)}</p><form id="line-destination-form" data-id="${esc(id)}">${inputField('line_user_id','LINE User ID',p.line_user_id||'','text','required pattern="U[0-9a-f]{32}" maxlength="33" autocomplete="off"')}<p class="help">ใช้ User ID จาก LINE OA ที่ขึ้นต้นด้วย U ตามด้วย 32 ตัวอักษร ไม่ใช่ LINE ID สำหรับค้นหาเพื่อน ผู้รับต้องเพิ่มเพื่อน LINE OA แล้ว</p>${inputField('reason','เหตุผลในการเปลี่ยน','','text','required maxlength="500"')}<p class="note">ข้อความครั้งถัดไป รวมถึงลิงก์เปลี่ยนรหัสผ่าน จะส่งไปยังบัญชีนี้ กรุณาตรวจว่าตรงกับเจ้าของบัญชี</p><div class="actions"><button type="button" class="secondary" data-action="close">ยกเลิก</button><button type="submit">บันทึกปลายทาง</button></div><div class="form-error"></div></form>`)}
const destinationEdit=editRecord;editRecord=function(entity,id){destinationEdit(entity,id);if(entity==='member'&&user?.role==='admin')document.getElementById('dialog').insertAdjacentHTML('beforeend',`<div class="actions"><button class="secondary small" data-line-destination="${esc(id)}">${icon('bell')} เปลี่ยน LINE ปลายทาง</button></div>`)};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.lineDestination)lineDestinationModal(b.dataset.lineDestination);if(b.hasAttribute('data-new-category')&&user?.role==='admin')modal('เพิ่มหมวดหมู่',`<form id="fund-category-form">${inputField('name','ชื่อหมวดหมู่','','text','required maxlength="100"')}<p class="help">ใช้ร่วมกันสำหรับรายรับและรายจ่าย ชื่อซ้ำจะใช้หมวดหมู่เดิม</p><div class="actions"><button type="button" class="secondary" data-action="close">ยกเลิก</button><button type="submit">เพิ่มหมวดหมู่</button></div><div class="form-error"></div></form>`);if(b.dataset.collectionId){const r=collectionRows().find(r=>r.id===b.dataset.collectionId);if(!r)return;const ps=db.payments.filter(p=>p.status==='approved'&&(db.references?.charges||db.charges).find(c=>c.id===p.charge_id)?.round_id===r.id);modal(r.title,`<div class="detail-grid">${detailCard('รับเงินแล้ว','฿'+money(r.amount))}${detailCard('รายการรับเงิน',r.count+' รายการ','check')}${detailCard('รับล่าสุด',esc(dateTime(r.last_at)),'clock')}</div>${user.role==='admin'?paymentTable(ps,true):'<p class="help">ยอดรวมการเก็บเงินของบิลนี้ ดูหลักฐานของคุณได้ในประวัติชำระเงิน</p>'}`)}});
document.addEventListener('submit',async e=>{const f=e.target;if(!['fund-category-form','line-destination-form'].includes(f.id))return;e.preventDefault();e.stopImmediatePropagation();if(user?.role!=='admin'||f.dataset.saving)return;f.dataset.saving='true';const b=f.querySelector('[type=submit]');b.disabled=true;try{const data=Object.fromEntries(new FormData(f));if(f.id==='fund-category-form'){const name=categoryName(data.name);if(cfg.mode==='live')await api('add-fund-category',{name});else{db.settings.fund_categories??=[];if(!fundCategoryNames().some(n=>n.toLocaleLowerCase('th')===name.toLocaleLowerCase('th')))db.settings.fund_categories.push(name)}}else{if(!/^U[0-9a-f]{32}$/.test(data.line_user_id))throw Error('LINE User ID ไม่ถูกต้อง');if(cfg.mode==='live')await api('set-line-destination',{id:f.dataset.id,...data});else{if(db.profiles.some(p=>p.id!==f.dataset.id&&p.line_user_id===data.line_user_id))throw Error('LINE นี้เชื่อมกับสมาชิกอื่นแล้ว');Object.assign(db.profiles.find(p=>p.id===f.dataset.id),{line_user_id:data.line_user_id,line_linked:true});audit('เปลี่ยน LINE ปลายทาง')}}await refresh();document.getElementById('dialog').close();render();toast('บันทึกเรียบร้อยแล้ว')}catch(err){f.querySelector('.form-error').innerHTML=`<p class="error">${esc(err.message)}</p>`}finally{b.disabled=false;delete f.dataset.saving}},true);
if(user)render();

document.addEventListener('click',async e=>{const b=e.target.closest('[data-delete-category],[data-confirm-delete-category],[data-cancel-delete-category]');if(!b||user?.role!=='admin')return;const box=document.getElementById('category-delete-confirm'),select=document.getElementById('edit-category');if(b.hasAttribute('data-cancel-delete-category')){box.hidden=true;return}if(b.hasAttribute('data-delete-category')){if(!select.value)return toast('เลือกหมวดหมู่ก่อน');box.dataset.category=select.value;box.hidden=false;return}const name=box.dataset.category;b.disabled=true;try{if(cfg.mode==='live')await api('delete-fund-category',{name});db.settings??={};db.settings.fund_categories=(db.settings.fund_categories||[]).filter(n=>categoryName(n).toLocaleLowerCase('th')!==name.toLocaleLowerCase('th'));db.settings.fund_categories_deleted??=[];db.settings.fund_categories_deleted.push(name.toLocaleLowerCase('th'));[...select.options].filter(o=>o.value===name).forEach(o=>o.remove());if(!select.options.length)select.add(new Option('เพิ่มหมวดหมู่เพื่อเลือก',''));box.hidden=true;toast('ลบหมวดหมู่แล้ว รายการเดิมยังอยู่')}catch(err){document.getElementById('delete-category-status').textContent=err.message}finally{b.disabled=false}});
