'use strict';
const fundContent=content;
content=function(){let html=fundContent();if(view!=='fund')return html;const rows=db.incomes||[];return html+`<div class="spacer"></div>`+panel('รายรับเพิ่มเติม',rows.length?`<div class="table-wrap"><table><thead><tr><th>รายการ</th><th>วันที่รับ</th><th>จำนวนเงิน</th>${user.role==='admin'?'<th>จัดการ</th>':''}</tr></thead><tbody>${rows.map(i=>`<tr><td>${esc(i.title)}<small>${esc(i.category)}${i.note?' · '+esc(i.note):''}</small></td><td>${date(i.received_on)}</td><td>฿${money(i.amount)}</td>${user.role==='admin'?`<td><div class="button-group"><button class="secondary small" data-income-edit="${esc(i.id)}">แก้ไขรายรับ</button>${deleteButton('income',i.id)}</div></td>`:''}</tr>`).join('')}</tbody></table></div>`:'<div class="empty">ยังไม่มีรายรับเพิ่มเติม</div>')};
function incomeModal(id){if(user.role!=='admin')return;const i=id?(db.incomes||[]).find(i=>i.id===id):{};if(!i)return;modal(id?'แก้ไขรายรับ':'เพิ่มรายรับกองกลาง',`<form id="fund-income" data-id="${esc(id||'')}">${inputField('title','รายการรายรับ',i.title||'','text','required maxlength="120"')}${inputField('category','ประเภท / แหล่งที่มา',i.category||'รายรับอื่น','text','required maxlength="100"')}${inputField('amount','จำนวนเงิน (บาท)',i.amount||'','number','required min="0.01" max="1000000" step="0.01"')}${inputField('received_on','วันที่รับเงิน',i.received_on||new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Bangkok'}),'date','required')}${inputField('note','หมายเหตุ',i.note||'','text','maxlength="500"')}${id?inputField('reason','เหตุผลที่แก้ไข','','text','required maxlength="500"'):''}<p class="help">รายรับนี้จะรวมในยอดกองกลางและรายงานรายเดือน</p><div class="actions"><button type="button" class="secondary" data-action="close">ยกเลิก</button><button type="submit">บันทึกรายรับ</button></div><div class="form-error"></div></form>`)}
const actionPaths={edit:'<path d="m16 3 5 5-12 12-6 1 1-6Z"/><path d="m14 5 5 5"/>',trash:'<path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7M14 10v7"/>',eye:'<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>',restore:'<path d="M3 10a9 9 0 1 1 2 8M3 4v6h6M12 7v5l3 2"/>',key:'<circle cx="8" cy="8" r="5"/><path d="m12 12 9 9M17 17l3-3M14 14l3-3"/>',send:'<path d="m3 3 18 9-18 9 3-9Zm3 9h15"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>',person:'<circle cx="9" cy="7" r="4"/><path d="M2 21v-3a7 7 0 0 1 14 0v3M20 8v8M16 12h8"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>'};
function iconActions(){const mapping={'data-edit':'edit','data-income-edit':'edit','data-delete-entity':'trash','data-restore-entity':'restore','data-review':'eye','data-receipt':'download','data-remind':'send','data-reset':'key','data-identity':'person','data-assign':'person','data-unlink-line':'close'};for(const [attr,kind] of Object.entries(mapping)){document.querySelectorAll(`button[${attr}]:not(.icon-button)`).forEach(b=>{const label=b.textContent.trim();b.setAttribute('aria-label',label);b.title=label;b.classList.add('icon-button');b.innerHTML=`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${actionPaths[kind]}</svg>`})}}
const fundRender=render;render=function(){db&&(db.incomes??=[]);fundRender();if(user?.role==='admin'&&view==='fund')$('.page-head')?.insertAdjacentHTML('beforeend',`<button data-new-income>${icon('plus')} เพิ่มรายรับ</button>`);iconActions()};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(b?.hasAttribute('data-new-income'))incomeModal();if(b?.dataset.incomeEdit)incomeModal(b.dataset.incomeEdit);queueMicrotask(iconActions)});
document.addEventListener('submit',async e=>{const f=e.target;if(f.id!=='fund-income')return;e.preventDefault();e.stopImmediatePropagation();const d=Object.fromEntries(new FormData(f)),buttons=[...f.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{if(cfg.mode==='live')await api('save-income',{...d,id:f.dataset.id||undefined});else{db.incomes??=[];if(f.dataset.id)Object.assign(db.incomes.find(i=>i.id===f.dataset.id),d);else db.incomes.push({...d,id:crypto.randomUUID(),amount:Number(d.amount)});audit('บันทึกรายรับกองกลาง')}await refresh();$('#dialog').close();render();toast('บันทึกรายรับเรียบร้อย')}catch(err){f.querySelector('.form-error').innerHTML=`<p class="error" role="alert">${esc(err.message)}</p>`}finally{buttons.forEach(b=>b.disabled=false)}},true);
