'use strict';
function statusSurface(id){let el=document.getElementById(id);if(!el){el=document.createElement('div');el.id=id;el.setAttribute('role','status');el.setAttribute('aria-live','polite');document.body.append(el)}if(el.parentElement!==document.body)document.body.append(el);if(typeof el.showPopover==='function')el.setAttribute('popover','manual');return el}
function showStatusSurface(el,visible){el.hidden=!visible;if(el.hasAttribute('popover')){try{if(visible&&!el.matches(':popover-open'))el.showPopover();if(!visible&&el.matches(':popover-open'))el.hidePopover()}catch{}}}
paintBusy=function(){const el=statusSurface('operation-status'),job=[...busyJobs.values()].at(-1);if(job)el.innerHTML=`<span class="operation-spinner" aria-hidden="true"></span><div><strong>${esc(job)}</strong><small>กรุณารอสักครู่</small></div>`;showStatusSurface(el,!!job)};
function messageResult(message){const text=String(message);const error=/ไม่สำเร็จ|ไม่ถูกต้อง|ผิดพลาด|หมดอายุ|ไม่สามารถ/.test(text),pending=/รอแอดมิน|รอตรวจ|เข้าคิว|ส่งกลับ|แก้ไขหลักฐาน|ยังไม่ได้เชื่อม/.test(text);const success=!error&&!pending&&/สำเร็จ|เรียบร้อย|แล้ว/.test(text);return {kind:error?'error':pending?'pending':success?'success':'info',title:error?'ทำรายการไม่สำเร็จ':pending?'บันทึกสถานะแล้ว':success?(/ยืนยัน.*(ชำระ|รับเงิน)/.test(text)?'ชำระเงินสำเร็จ':'ทำรายการสำเร็จ'):'แจ้งให้ทราบ'}}
let resultTimer;toast=function(message){const old=document.getElementById('toast');if(old)old.style.display='none';clearTimeout(toastTimer);clearTimeout(resultTimer);const result=messageResult(message),el=statusSurface('result-status');el.className=result.kind;el.innerHTML=`<span class="result-mark" aria-hidden="true">${result.kind==='success'?'<svg viewBox="0 0 24 24"><path d="m5 12 4 4L19 6"/></svg>':icon(result.kind==='error'?'bell':'history')}</span><div><strong>${esc(result.title)}</strong><p>${esc(message)}</p></div><button type="button" class="ghost small" data-result-close aria-label="ปิดข้อความ">✕</button>`;showStatusSurface(el,true);resultTimer=setTimeout(()=>showStatusSurface(el,false),result.kind==='success'?3800:6500)};
let sidebarCompact=false;try{sidebarCompact=localStorage.getItem('finance-sidebar-compact')==='true'}catch{}
const navigationGroups=[['ภาพรวม',['dashboard']],['การเงิน',['rounds','bills','review','history','fund','reports']],['สมาชิกและข้อความ',['members','notifications','profile']],['ดูแลระบบ',['audit','trash','settings']]];
function polishNavigation(){const sidebar=document.querySelector('.sidebar'),nav=sidebar?.querySelector('.nav');if(!sidebar||!nav)return;const buttons=[...nav.querySelectorAll('button[data-view]')];nav.innerHTML='';for(const [title,views]of navigationGroups){const groupButtons=buttons.filter(b=>views.includes(b.dataset.view));if(!groupButtons.length)continue;const group=document.createElement('section');group.className='nav-section';group.innerHTML=`<h2>${title}</h2>`;for(const b of groupButtons){const text=b.textContent.trim();b.setAttribute('aria-label',text);b.title=text;for(const n of [...b.childNodes])if(n.nodeType===3){const span=document.createElement('span');span.className='nav-label';span.textContent=n.textContent;n.replaceWith(span)}group.append(b)}nav.append(group)}const tools=document.createElement('div');tools.className='sidebar-tools';tools.innerHTML=`<span>เมนูหลัก</span><button type="button" class="ghost small" data-sidebar-toggle aria-label="${sidebarCompact?'ขยาย':'ย่อ'}แถบเมนู" aria-expanded="${!sidebarCompact}" title="ย่อหรือขยายแถบเมนู">${icon('menu')}</button>`;nav.before(tools);const logout=sidebar.querySelector('.logout-button');if(logout){logout.setAttribute('aria-label','ออกจากระบบ');logout.title='ออกจากระบบ';for(const n of [...logout.childNodes])if(n.nodeType===3){const span=document.createElement('span');span.className='nav-label';span.textContent=n.textContent;n.replaceWith(span)}}document.querySelector('.layout')?.classList.toggle('sidebar-compact',sidebarCompact)}
const polishRender=render;render=function(){polishRender();polishNavigation()};
document.addEventListener('click',e=>{if(e.target.closest('[data-result-close]'))showStatusSurface(document.getElementById('result-status'),false);if(e.target.closest('[data-sidebar-toggle]')){if(window.innerWidth<=720){document.querySelector('.layout')?.classList.remove('menu-open');return}sidebarCompact=!sidebarCompact;try{localStorage.setItem('finance-sidebar-compact',String(sidebarCompact))}catch{}document.querySelector('.layout')?.classList.toggle('sidebar-compact',sidebarCompact);const b=document.querySelector('[data-sidebar-toggle]');b.setAttribute('aria-expanded',String(!sidebarCompact));b.setAttribute('aria-label',(sidebarCompact?'ขยาย':'ย่อ')+'แถบเมนู')}});
billMemberFields=function(selected){const members=db.profiles.filter(p=>p.role==='member'&&p.active!==false);return `<fieldset class="bill-members searchable-members"><legend>สมาชิกที่ต้องชำระ</legend><div class="member-picker-top"><input type="search" data-member-query placeholder="ค้นหาชื่อหรือรหัสนักศึกษา" aria-label="ค้นหาสมาชิกที่ต้องชำระ"><div class="member-picker-tools"><span data-member-count aria-live="polite">เลือก ${members.filter(p=>selected.includes(p.id)).length} / ${members.length} คน</span><div class="button-group"><button type="button" class="secondary small" data-bill-select="all">ทั้งหมด</button><button type="button" class="secondary small" data-bill-select="none">ล้าง</button><button type="button" class="secondary small" data-member-visible>เลือกผลค้นหา</button></div></div></div><div class="member-picker-list">${members.map(p=>`<label data-member-row data-search="${esc((p.name+' '+p.student_id).toLocaleLowerCase('th'))}"><input type="checkbox" name="profile_ids" value="${esc(p.id)}" ${selected.includes(p.id)?'checked':''}><span>${esc(p.name)}<small>${esc(p.student_id)} · ปี ${esc(p.year||'—')}</small></span></label>`).join('')}<p class="help" data-member-empty ${members.length?'hidden':''}>${members.length?'ไม่พบสมาชิกที่ค้นหา':'เพิ่มสมาชิกก่อนสร้างบิล'}</p></div></fieldset>`};
function refreshMemberPicker(field){if(!field)return;const rows=[...field.querySelectorAll('[data-member-row]')],query=field.querySelector('[data-member-query]').value.trim().toLocaleLowerCase('th');rows.forEach(row=>row.hidden=!row.dataset.search.includes(query));field.querySelector('[data-member-empty]').hidden=rows.some(r=>!r.hidden);field.querySelector('[data-member-count]').textContent=`เลือก ${field.querySelectorAll('[name=profile_ids]:checked').length} / ${rows.length} คน${query?` · พบ ${rows.filter(r=>!r.hidden).length}`:''}`}
document.addEventListener('input',e=>{if(e.target.matches('[data-member-query]'))refreshMemberPicker(e.target.closest('.bill-members'))});
document.addEventListener('change',e=>{if(e.target.name==='profile_ids')refreshMemberPicker(e.target.closest('.bill-members'))});
document.addEventListener('click',e=>{const b=e.target.closest('[data-bill-select],[data-member-visible]');if(!b)return;const field=b.closest('.bill-members');if(b.hasAttribute('data-member-visible'))field.querySelectorAll('[data-member-row]:not([hidden]) input').forEach(i=>i.checked=true);refreshMemberPicker(field)});
const polishContent=content;content=function(){let html=polishContent();if(user?.role!=='admin'||view!=='rounds')return html;const t=document.createElement('template');t.innerHTML=html;const completed=[];t.content.querySelectorAll('.round-summary').forEach((summary,index)=>{const r=db.rounds[index];if(!r)return;const charges=db.charges.filter(c=>c.round_id===r.id&&!c.deleted_at),count=charges.filter(c=>balance(c)<=0).length,total=charges.length,pct=total?Math.round(count/total*100):0,done=total>0&&count===total;summary.insertAdjacentHTML('afterend',`<div class="bill-payment-progress ${done?'is-complete':''}"><div><strong>${done?'ชำระครบทุกคน':'ความคืบหน้าการชำระ'}</strong><span>ชำระแล้ว ${count} / ${total} คน</span></div><div class="progress" role="progressbar" aria-label="ผู้ชำระบิล ${esc(r.title)}" aria-valuenow="${count}" aria-valuemin="0" aria-valuemax="${total||1}"><span style="width:${pct}%"></span></div></div>`);if(done){const panel=summary.closest('.panel');if(panel)completed.push(panel)}});if(completed.length){const details=document.createElement('details');details.className='completed-bills';details.innerHTML=`<summary><span>${icon('check')} บิลที่ชำระครบแล้ว</span><span>${completed.length} บิล</span></summary><div class="stack"></div>`;completed.forEach(p=>details.querySelector('.stack').append(p));t.content.append(details)}return t.innerHTML};
if(user)render();
