'use strict';
let lineLoginEnabled=false;
const lineLoginRender=render;render=function(){lineLoginRender();if(!user){const form=document.getElementById('login-form');if(form&&!document.getElementById('line-login-button'))form.insertAdjacentHTML('afterend','<button type="button" id="line-login-button" class="line-login-button">เข้าสู่ระบบด้วย LINE</button>')}else if(lineLoginEnabled)document.querySelectorAll('[data-action="link-line"]').forEach(b=>b.textContent=user.line_linked?'เปลี่ยนบัญชี LINE':'เชื่อมบัญชีด้วย LINE Login')};
document.addEventListener('click',async e=>{const b=e.target.closest('#line-login-button,[data-action="link-line"]');if(!b)return;if(b.dataset.action==='link-line'&&!lineLoginEnabled)return;e.preventDefault();e.stopImmediatePropagation();b.disabled=true;try{if(cfg.mode!=='live')throw Error('โหมดทดลองไม่เชื่อมต่อ LINE จริง');if(user)await ensureLiveSession();await FinanceLine.start(user?'link':'login',{accessToken:user?token:null,remember:document.querySelector('[name=remember]')?.checked??true})}catch(err){toast(err.message);b.disabled=false}},true);
if(cfg.mode==='live')FinanceLine.request({action:'status'}).then(r=>{lineLoginEnabled=r.enabled;if(user&&lineLoginEnabled)document.querySelectorAll('[data-action="link-line"]').forEach(b=>b.textContent=user.line_linked?'เปลี่ยนบัญชี LINE':'เชื่อมบัญชีด้วย LINE Login')}).catch(()=>{});
render();

let ownLineProfile=null,ownLineProfileOwner='',ownLineProfilePending=false;
function paintLineProfile(){if(!user||view!=='profile')return;const button=document.querySelector('[data-action="link-line"]'),body=button?.closest('.panel-body');if(!body)return;button.textContent=user.line_linked?'เปลี่ยนบัญชี LINE':'เชื่อมบัญชี LINE';let status=body.querySelector('.line-account-status');if(!status){body.querySelectorAll('p').forEach(p=>p.remove());body.insertAdjacentHTML('afterbegin','<div class="line-account-status" role="status"></div>');status=body.querySelector('.line-account-status')}const info=ownLineProfileOwner===user.id?ownLineProfile:null;status.innerHTML=user.line_linked?`<span class="badge approved">เชื่อมบัญชี LINE แล้ว</span><div class="line-account-name">${icon('person')}<strong>${esc(info?.display_name|| (info?'ยังดึงชื่อ LINE ไม่ได้':'กำลังตรวจสอบชื่อ LINE…'))}</strong></div>`:'<p>ยังไม่ได้เชื่อมบัญชี LINE</p><p class="help">เชื่อมเพื่อเข้าสู่ระบบและรับการแจ้งเตือน</p>';}
const lineProfileRender=render;render=function(){lineProfileRender();paintLineProfile();if(!user||view!=='profile'||!user.line_linked||ownLineProfilePending||(ownLineProfileOwner===user.id&&ownLineProfile))return;const id=user.id;ownLineProfilePending=true;(cfg.mode==='live'?api('line-profile'):Promise.resolve({linked:true,display_name:'LINE ตัวอย่าง'})).then(data=>{if(user?.id===id){ownLineProfileOwner=id;ownLineProfile=data;paintLineProfile()}}).catch(()=>{if(user?.id===id){ownLineProfileOwner=id;ownLineProfile={linked:true};paintLineProfile()}}).finally(()=>ownLineProfilePending=false)};
