'use strict';
// Management screens share the existing authenticated API and financial calculations.
const originalContent=content,originalRender=render,originalRefresh=refresh;
const settingKeys=['siteName','bankName','accountName','accountNumber','paymentQrUrl','lineOaUrl'];
refresh=async function(){await originalRefresh();for(const key of settingKeys)if(typeof db?.settings?.[key]==='string')cfg[key]=db.settings[key]};
render=function(){originalRender();document.title=cfg.siteName||'finance MEDTECH';document.querySelectorAll('.brand').forEach(el=>{el.textContent=cfg.siteName||'finance MEDTECH';el.insertAdjacentHTML('beforeend','<span>STUDENT FINANCE</span>')});const title=$('.topbar-title');if(title)title.textContent=cfg.siteName||'finance MEDTECH'};
const inputField=(key,label,value='',type='text',attrs='')=>`<label for="edit-${key}">${label}</label><input id="edit-${key}" name="${key}" type="${type}" value="${esc(value)}" ${attrs}>`;
const selectField=(key,label,value,options)=>`<label for="edit-${key}">${label}</label><select id="edit-${key}" name="${key}">${options.map(([v,t])=>`<option value="${esc(v)}" ${String(v)===String(value)?'selected':''}>${t}</option>`).join('')}</select>`;
const editButton=(entity,id)=>`<button class="secondary small" data-edit="${entity}" data-id="${esc(id)}">แก้ไข</button>`;
const recordForm=(entity,id,body)=>`<form id="record-edit" data-entity="${entity}" data-id="${esc(id)}">${body}<div class="actions"><button type="button" class="secondary" data-action="close">ยกเลิก</button><button type="submit">บันทึกการแก้ไข</button></div><div class="form-error"></div></form>`;
let reportMonth='',reportOutstanding=false,importRows=[];
const monthKey=s=>{const parts=new Intl.DateTimeFormat('en',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit'}).formatToParts(new Date(s));return parts.find(p=>p.type==='year').value+'-'+parts.find(p=>p.type==='month').value};
function reportData(){const payments=db.payments.filter(p=>p.status==='approved'&&(!reportMonth||monthKey(p.reviewed_at||p.created_at)===reportMonth));const expenses=db.expenses.filter(e=>!e.voided&&(!reportMonth||e.spent_on.slice(0,7)===reportMonth));const incomes=(db.incomes||[]).filter(i=>!reportMonth||i.received_on.slice(0,7)===reportMonth);return {payments,expenses,incomes,income:incomes.filter(i=>(i.workflow_status||'settled')==='settled').reduce((s,i)=>s+Number(i.amount),0)+payments.reduce((s,p)=>s+Number(p.amount),0),expense:expenses.filter(e=>(e.workflow_status||'settled')==='settled').reduce((s,e)=>s+Number(e.amount),0)}}
function reportCharges(){return db.charges.filter(c=>!reportOutstanding||balance(c)>0)}
content=function(){if(user.role!=='admin'){if(view==='fund'){const all=db.expenses;db.expenses=all.filter(e=>!e.voided);try{return originalContent()}finally{db.expenses=all}}return originalContent()};switch(view){
case 'rounds':return head('รายการบิล','กำหนดรายการ จัดการยอด และปิดรับชำระ','<button data-action="new-round">'+icon('plus')+' สร้างบิล</button>')+`<div class="stack">${db.rounds.map(r=>panel(esc(r.title),`<div class="panel-body"><div class="split"><span class="help">${esc(r.description)}</span><span class="badge ${r.archived?'unpaid':'approved'}">${r.archived?'ปิดรับชำระ':'เปิดรับชำระ'}</span></div><div class="round-summary"><div><small>ยอดต่อคน</small><strong>฿${money(r.amount)}</strong></div><div><small>ครบกำหนด</small><strong>${date(r.due_date)}</strong></div><div><small>สมาชิกในรอบ</small><strong>${db.charges.filter(c=>c.round_id===r.id).length} คน</strong></div></div></div>`,editButton('round',r.id))).join('')||'<div class="empty">เริ่มด้วยการสร้างบิลแรก</div>'}</div>`;
case 'members':return head('สมาชิก','ดูแลบัญชี สิทธิ์ และยอดค้างชำระ','<div class="button-group"><button class="secondary" data-manage="import">นำเข้า CSV</button><button data-action="new-member">'+icon('plus')+' เพิ่มสมาชิก</button></div>')+`<div class="toolbar"><input id="member-search" placeholder="ค้นหาชื่อหรือรหัสนักศึกษา" aria-label="ค้นหาสมาชิก" value="${esc(filter)}"></div>`+panel('บัญชีทั้งหมด',`<div class="table-wrap"><table><thead><tr><th>สมาชิก</th><th>ชั้นปี / สิทธิ์</th><th>สถานะ</th><th>ยอดค้าง</th><th>จัดการ</th></tr></thead><tbody>${db.profiles.filter(p=>p.name.includes(filter)||p.student_id.includes(filter)).map(p=>`<tr><td>${esc(p.name)}<small>${esc(p.student_id)} · LINE ${p.line_linked?'เชื่อมแล้ว':'ยังไม่เชื่อม'}</small></td><td>${esc(p.year||'—')} / ${p.role==='admin'?'แอดมิน':'สมาชิก'}</td><td><span class="badge ${p.active===false?'unpaid':'approved'}">${p.active===false?'ปิดบัญชี':'ใช้งาน'}</span></td><td>฿${money(db.charges.filter(c=>c.profile_id===p.id).reduce((s,c)=>s+balance(c),0))}</td><td><div class="button-group">${editButton('member',p.id)}${p.role==='member'?`<button class="ghost small" data-reset="${esc(p.id)}">รีเซ็ตรหัส</button><button class="ghost small" data-assign="${esc(p.id)}">เพิ่มบิล</button><button class="ghost small" data-remind="${esc(p.id)}">แจ้งเตือน</button><button class="ghost small" data-identity="${esc(p.id)}">แก้รหัสนักศึกษา</button>`:''}</div></td></tr>`).join('')}</tbody></table></div>`);
case 'fund':return head('เงินกองกลาง','รับเงิน ใช้จ่าย และเก็บประวัติทุกการแก้ไข','<button data-action="new-expense">'+icon('plus')+' บันทึกรายจ่าย</button>')+`<div class="grid-two"><div>${panel('รายจ่ายทั้งหมด',db.expenses.length?`<div class="table-wrap"><table><thead><tr><th>รายการ</th><th>วันที่</th><th>ยอด</th><th>จัดการ</th></tr></thead><tbody>${db.expenses.map(e=>`<tr class="${e.voided?'voided':''}"><td>${esc(e.title)}<small>${esc(e.category)}${e.voided?' · ยกเลิกแล้ว':''}</small></td><td>${date(e.spent_on)}</td><td><div class="ledger-amount-status">฿${money(e.amount)} ${fundWorkflowBadge(e,'expense')}</div></td><td><div class="button-group">${editButton('expense',e.id)}${e.drive_file_id?`<button class="ghost small" data-expense-file="${esc(e.id)}">หลักฐาน</button>`:''}</div></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">ยังไม่มีรายจ่าย</div>')}</div>${fundSummary()}</div>`;
case 'settings':return head('ตั้งค่าระบบ','ปรับข้อมูลเว็บ บัญชีรับเงิน QR และ LINE OA')+panel('ข้อมูลสาธารณะของเว็บ',`<form id="settings-edit" class="panel-body">${inputField('siteName','ชื่อเว็บ',cfg.siteName||'finance MEDTECH','text','required maxlength="80"')}<div class="form-grid">${inputField('bankName','ธนาคาร / ประเภทพร้อมเพย์',cfg.bankName,'text','required maxlength="120"')}${inputField('accountName','ชื่อบัญชีผู้รับ',cfg.accountName,'text','required maxlength="120"')}</div>${inputField('accountNumber','เลขบัญชี / หมายเลขพร้อมเพย์',cfg.accountNumber,'text','required maxlength="40"')}${inputField('lineOaUrl','ลิงก์เพิ่มเพื่อน LINE OA',cfg.lineOaUrl,'url','maxlength="500"')}<label for="qr-file">QR หลักรับเงิน</label><input id="qr-file" name="file" type="file" accept="image/png,image/jpeg,image/webp"><p class="help">ใช้เมื่อไม่มี QR ตรงกับยอดชำระ · เลือกภาพไม่ระบุยอด ไม่เกิน 1 MB หรือเว้นว่างเพื่อใช้ภาพเดิม</p>${cfg.paymentQrUrl?`<img class="settings-qr" src="${esc(cfg.paymentQrUrl)}" alt="QR รับเงินปัจจุบัน">`:''}<p class="note">เมื่อเปลี่ยนบัญชีรับเงิน ให้เปลี่ยน QR ให้ตรงกัน และปรับบัญชีรับเงินใน SlipOK ด้วย การตั้งค่านี้แสดงให้สมาชิกเห็นหลังเข้าสู่ระบบ</p><div class="actions"><button type="button" class="secondary" data-action="password">เปลี่ยนรหัสผ่านของฉัน</button><button type="submit">บันทึกการตั้งค่า</button></div><div class="form-error"></div></form>`);
case 'reports':{const r=reportData();return head('รายงานการเงิน','รายรับและรายจ่ายตามเดือน พร้อมยอดค้างปัจจุบัน','<div class="button-group"><button class="secondary" data-manage="monthly-export">รายเดือน CSV</button><button data-manage="outstanding-export">ยอดค้าง CSV</button></div>')+`<div class="toolbar"><label>เดือนของรายรับ / รายจ่าย<input id="report-month" type="month" value="${esc(reportMonth)}"></label><button class="secondary small" data-manage="all-months">ทุกเดือน</button><label class="checkbox-label"><input id="report-outstanding" type="checkbox" ${reportOutstanding?'checked':''}> เฉพาะรายการค้างชำระ</label></div><div class="stats">${stat('รับเงินที่ยืนยัน',r.income,reportMonth||'ทุกเดือน',true)}${stat('รายจ่าย',r.expense,'ไม่รวมรายการยกเลิก')}${stat('รับสุทธิในช่วง',r.income-r.expense,'รายรับลบรายจ่ายในช่วงที่เลือก')}</div>`+panel('ยอดเรียกเก็บปัจจุบัน',`<div class="table-wrap"><table><thead><tr><th>สมาชิก / รายการ</th><th>เรียกเก็บ</th><th>ชำระแล้ว</th><th>ค้าง</th><th>จัดการ</th></tr></thead><tbody>${reportCharges().map(c=>{const p=db.profiles.find(p=>p.id===c.profile_id);return `<tr><td>${esc(p?.name)}<small>${esc(p?.student_id)} · ${esc(round(c.round_id).title)}</small></td><td>${money(chargeTotal(c))}</td><td>${money(paid(c))}</td><td>${money(balance(c))}</td><td>${editButton('charge',c.id)}</td></tr>`}).join('')}</tbody></table></div>`)+`<div class="spacer"></div>`+panel('รายการในช่วงที่เลือก',`<div class="table-wrap"><table class="report-period-table"><thead><tr><th>รายการ</th><th>วันที่</th><th>ประเภท</th><th>จำนวนเงิน</th><th>จัดการ</th></tr></thead><tbody>${r.payments.map(p=>`<tr><td>${esc(round((db.references?.charges||db.charges).find(c=>c.id===p.charge_id)?.round_id).title)}<small>${esc((db.references?.profiles||db.profiles).find(person=>person.id===p.profile_id)?.name)}</small></td><td>${dateTime(p.reviewed_at||p.created_at)}</td><td>รับ</td><td>${money(p.amount)}</td><td><div class="button-group">${editButton('payment',p.id)}${deleteButton('payment',p.id)}</div></td></tr>`).join('')}${r.incomes.map(i=>`<tr><td>${esc(i.title)}</td><td>${date(i.received_on)}</td><td>รับเพิ่มเติม</td><td><div class="ledger-amount-status">${money(i.amount)} ${fundWorkflowBadge(i,'income')}</div></td><td><div class="button-group"><button class="secondary small" data-income-edit="${esc(i.id)}">แก้ไขรายรับ</button>${deleteButton('income',i.id)}</div></td></tr>`).join('')}${r.expenses.map(e=>`<tr><td>${esc(e.title)}</td><td>${date(e.spent_on)}</td><td>จ่าย</td><td><div class="ledger-amount-status">${money(e.amount)} ${fundWorkflowBadge(e,'expense')}</div></td><td><div class="button-group">${editButton('expense',e.id)}${deleteButton('expense',e.id)}</div></td></tr>`).join('')}</tbody></table></div>`)}
case 'audit':return head('ประวัติการแก้ไข','ผู้แก้ไข วันเวลา และข้อมูลก่อน–หลัง')+panel('กิจกรรมล่าสุด',`<div class="panel-body">${db.audit.map(a=>`<div class="audit-entry"><strong>${esc(a.action)}</strong><p class="help">${esc(a.actor)} · ${new Date(a.created_at).toLocaleString('th-TH',{timeZone:'Asia/Bangkok'})}</p>${a.details?`<details><summary>ดูการเปลี่ยนแปลง</summary><pre>${esc(JSON.stringify(a.details,(key,value)=>key==='paymentQrUrl'&&String(value).startsWith('data:')?'[ภาพ QR]':value,2))}</pre></details>`:''}</div>`).join('')||'<div class="empty">ยังไม่มีประวัติ</div>'}</div>`);
default:return originalContent()}};
// Closed rounds retain their balances and payment history while preventing new uploads.
const originalBillRow=billRow;billRow=function(c){if(!round(c.round_id).archived)return originalBillRow(c);return `<div class="bill"><div class="bill-info"><h3>${esc(round(c.round_id).title)}</h3><span class="help">ปิดรับชำระ · ติดต่อผู้ดูแล</span></div><div class="bill-right">฿${money(balance(c))}</div></div>`};
const originalFundSummary=fundSummary;fundSummary=function(){if(cfg.mode==='demo'){const total=db.expenses.filter(e=>!e.voided&&(e.workflow_status||'settled')==='settled').reduce((s,e)=>s+Number(e.amount),0);db.fund_totals={income:(db.incomes||[]).filter(i=>(i.workflow_status||'settled')==='settled').reduce((s,i)=>s+Number(i.amount),0)+db.payments.filter(p=>p.status==='approved').reduce((s,p)=>s+Number(p.amount),0),expense:total}}return originalFundSummary()};
const originalReview=reviewModal;reviewModal=function(id){originalReview(id);if(user.role==='admin')$('#dialog').insertAdjacentHTML('beforeend',`<div class="actions">${editButton('payment',id)}</div>`)};
function editRecord(entity,id){if(user.role!=='admin')return;const tables={member:'profiles',round:'rounds',expense:'expenses',payment:'payments',charge:'charges'},r=db[tables[entity]]?.find(r=>r.id===id);if(!r)return;let body='';
if(entity==='member')body=`<p class="help">รหัสนักศึกษา ${esc(r.student_id)} · ใช้ปุ่มแก้รหัสนักศึกษาหากต้องเปลี่ยนข้อมูลเข้าสู่ระบบ</p>`+inputField('name','ชื่อ–นามสกุล',r.name,'text','required maxlength="120"')+selectField('year','ชั้นปี',r.year||'',[['','ไม่ระบุ'],['1','1'],['2','2'],['3','3'],['4','4']])+selectField('role','สิทธิ์',r.role,[['member','สมาชิก'],['admin','แอดมิน']])+selectField('active','สถานะบัญชี',r.active!==false?'true':'false',[['true','เปิดใช้งาน'],['false','ปิดใช้งาน']]);
if(entity==='round')body=inputField('title','ชื่อบิล',r.title,'text','required maxlength="120"')+inputField('description','รายละเอียด',r.description||'','text','maxlength="1000"')+inputField('amount','ยอดต่อคน (บาท)',r.amount,'number','required min="0.01" step="0.01"')+inputField('due_date','วันครบกำหนด',r.due_date,'date','required')+selectField('archived','การรับชำระ',String(!!r.archived),[['false','เปิดรับชำระ'],['true','ปิดรับชำระ']])+'<p class="help">ยอดใหม่ใช้กับสมาชิกทั้งหมดในรอบ แก้ยอดได้เมื่อยังไม่มีการชำระหรือรายการรอตรวจ</p>';
if(entity==='expense')body=inputField('title','ชื่อรายจ่าย',r.title,'text','required maxlength="120"')+inputField('category','หมวดหมู่',r.category,'text','required maxlength="100"')+inputField('amount','จำนวนเงิน',r.amount,'number','required min="0.01" step="0.01"')+inputField('spent_on','วันที่จ่าย',r.spent_on,'date','required')+inputField('note','หมายเหตุ',r.note||'','text','maxlength="500"')+selectField('voided','สถานะรายการ',String(!!r.voided),[['false','ใช้งาน / รวมในยอดกองกลาง'],['true','ยกเลิก / ไม่นับยอด']])+inputField('reason','เหตุผลที่แก้ไข','','text','required maxlength="500"')+'<label for="expense-replace">หลักฐานใหม่ (ไม่เลือกเพื่อเก็บภาพเดิม)</label><input id="expense-replace" name="file" type="file" accept="image/jpeg,image/png,image/webp"><p class="help">หลักฐานเดิมยังเก็บไว้ในประวัติ</p>';
if(entity==='payment')body=inputField('note','หมายเหตุรายการ',r.note||'','text','maxlength="500"')+'<p class="help">ยอดเงิน เลขอ้างอิง และสถานะที่ยืนยันแล้วเก็บตามธุรกรรมเดิม</p>';
if(entity==='charge')body=inputField('amount','ยอดเรียกเก็บเฉพาะคนนี้',r.amount,'number','required min="0.01" step="0.01"')+inputField('reason','เหตุผลที่เปลี่ยนยอด','','text','required maxlength="500"')+'<p class="help">เปลี่ยนได้เฉพาะรายการที่ยังไม่มีการชำระหรือรอตรวจ</p>';
modal('แก้ไขข้อมูล',recordForm(entity,id,body))}
function parseCsv(source){const rows=[];let row=[],field='',quoted=false;const s=source.replace(/^\uFEFF/,'');for(let i=0;i<s.length;i++){const c=s[i];if(c==='"'){if(quoted&&s[i+1]==='"'){field+='"';i++}else if(quoted)quoted=false;else if(field==='')quoted=true;else throw Error('เครื่องหมายคำพูดใน CSV ไม่ถูกต้อง')}else if(c===','&&!quoted){row.push(field);field=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&s[i+1]==='\n')i++;row.push(field);if(row.some(v=>v.trim()))rows.push(row);row=[];field=''}else field+=c}if(quoted)throw Error('CSV ปิดเครื่องหมายคำพูดไม่ครบ');row.push(field);if(row.some(v=>v.trim()))rows.push(row);return rows}
function csvMembers(s){const rows=parseCsv(s),headers=rows.shift()?.map(v=>v.trim());const required=['student_id','name','year','password'];if(!headers||required.some(h=>!headers.includes(h))||new Set(headers).size!==headers.length)throw Error('หัวตารางต้องมี student_id,name,year,password');if(!rows.length||rows.length>25)throw Error('นำเข้าได้ครั้งละ 1–25 คน');const seen=new Set();return rows.map((row,i)=>{if(row.length!==headers.length)throw Error(`แถว ${i+2}: จำนวนช่องไม่ตรงหัวตาราง`);const r=Object.fromEntries(headers.map((h,j)=>[h,row[j].trim()]));if(!/^\d{5,20}$/.test(r.student_id)||!r.name||r.name.length>120||!['1','2','3','4'].includes(r.year)||r.password.length<6||r.password.length>128||seen.has(r.student_id))throw Error(`แถว ${i+2}: ตรวจรหัสนักศึกษา ชื่อ ชั้นปี รหัสผ่าน 6 ตัวขึ้นไป หรือรายการซ้ำ`);seen.add(r.student_id);return r})}
function importModal(){importRows=[];modal('นำเข้าสมาชิก CSV',`<p class="help">ใช้หัวตาราง student_id,name,year,password · ครั้งละไม่เกิน 25 คน<br>รหัสนักศึกษาเป็นข้อความเพื่อเก็บเลขศูนย์นำหน้า รหัสผ่านอย่างน้อย 6 ตัวอักษร</p><button class="secondary small" data-manage="template">ดาวน์โหลดแม่แบบ</button><form id="member-import"><label for="member-csv">ไฟล์ CSV (UTF-8)</label><input id="member-csv" type="file" accept=".csv,text/csv" required><div id="import-preview"></div><div class="actions"><button type="submit" id="import-submit" disabled>ยืนยันนำเข้ารายชื่อ</button></div><div class="form-error"></div></form>`)}
function downloadCsv(name,rows){const safe=v=>{let s=String(v??'');if(/^[\s]*[=+@\-]/.test(s)||/^[\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'};const url=URL.createObjectURL(new Blob(['\ufeff'+rows.map(r=>r.map(safe).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.edit)editRecord(b.dataset.edit,b.dataset.id);if(b.dataset.reset){const p=db.profiles.find(p=>p.id===b.dataset.reset);modal('รีเซ็ตรหัสผ่าน',`<p>สมาชิก ${esc(p.name)} · ${esc(p.student_id)}</p><p class="help">ยืนยันตัวตนของสมาชิกก่อนดำเนินการ และส่งรหัสใหม่ให้เจ้าของบัญชีโดยตรง</p><form id="member-reset" data-id="${esc(p.id)}">${inputField('password','รหัสผ่านใหม่','','password','required minlength="6" maxlength="128" autocomplete="new-password"')}<div class="actions"><button type="submit">ตั้งรหัสผ่านใหม่</button></div><div class="form-error"></div></form>`)}
if(b.dataset.identity){const p=db.profiles.find(p=>p.id===b.dataset.identity);modal('แก้รหัสนักศึกษา',`<form id="member-identity" data-id="${esc(p.id)}"><p class="help">ประวัติการชำระและ LINE จะยังผูกกับบัญชีเดิม การเข้าสู่ระบบครั้งต่อไปใช้รหัสใหม่</p>${inputField('student_id','รหัสนักศึกษาใหม่',p.student_id,'text','required pattern="[0-9]{5,20}"')}<div class="actions"><button type="submit">บันทึกรหัสใหม่</button></div><div class="form-error"></div></form>`)}
if(b.dataset.assign){const p=db.profiles.find(p=>p.id===b.dataset.assign),rounds=db.rounds.filter(r=>!r.archived&&!db.charges.some(c=>c.profile_id===p.id&&c.round_id===r.id));modal('เพิ่มสมาชิกในรอบ',rounds.length?`<form id="member-assign" data-id="${esc(p.id)}"><p>${esc(p.name)}</p>${selectField('round_id','เลือกรอบ','',rounds.map(r=>[r.id,esc(r.title)+' · ฿'+money(r.amount)]))}<div class="actions"><button type="submit">เพิ่มรายการเรียกเก็บ</button></div><div class="form-error"></div></form>`:'<div class="empty">ไม่มีรอบที่สามารถเพิ่มได้</div>')}
switch(b.dataset.manage){case'import':importModal();break;case'template':downloadCsv('member-template.csv',[['student_id','name','year','password']]);break;case'all-months':reportMonth='';render();break;case'outstanding-export':downloadCsv('outstanding.csv',[['รหัสนักศึกษา','ชื่อ','รอบ','เรียกเก็บ','ชำระแล้ว','ค้าง'],...db.charges.filter(c=>balance(c)>0).map(c=>{const p=db.profiles.find(p=>p.id===c.profile_id);return [p?.student_id,p?.name,round(c.round_id).title,chargeTotal(c),paid(c),balance(c)]})]);break;case'monthly-export':{const r=reportData();downloadCsv('monthly-'+(reportMonth||'all')+'.csv',[['วันที่','รายการ','ประเภท','จำนวนเงิน','สถานะ'],...r.payments.map(p=>[dateTime(p.reviewed_at||p.created_at),round((db.references?.charges||db.charges).find(c=>c.id===p.charge_id)?.round_id).title,'รับ',p.amount,'รับเงินแล้ว']),...r.incomes.map(i=>[i.received_on,i.title,'รับเพิ่มเติม',i.amount,fundWorkflowText(i,'income')]),...r.expenses.map(e=>[e.spent_on,e.title,'จ่าย',e.amount,fundWorkflowText(e,'expense')])]);break}}});
document.addEventListener('change',async e=>{if(e.target.id==='report-month'){reportMonth=e.target.value;render()}if(e.target.id==='report-outstanding'){reportOutstanding=e.target.checked;render()}if(e.target.id==='member-csv'){const f=e.target.files[0];importRows=[];$('#import-submit').disabled=true;try{if(!f||f.size>256*1024)throw Error('CSV ต้องไม่เกิน 256 KB');importRows=csvMembers(await f.text());$('#import-preview').innerHTML=`<div class="note">พร้อมนำเข้า ${importRows.length} คน · บัญชีเดิมจะข้าม</div><div class="table-wrap"><table><thead><tr><th>รหัสนักศึกษา</th><th>ชื่อ</th><th>ปี</th></tr></thead><tbody>${importRows.map(r=>`<tr><td>${esc(r.student_id)}</td><td>${esc(r.name)}</td><td>${esc(r.year)}</td></tr>`).join('')}</tbody></table></div>`;$('#import-submit').disabled=false;$('#member-import .form-error').textContent=''}catch(err){$('#import-preview').textContent='';$('#member-import .form-error').textContent=err.message}}});
document.addEventListener('submit',async e=>{const f=e.target;if(!['record-edit','settings-edit','member-import','member-reset','member-assign','member-identity'].includes(f.id))return;e.preventDefault();e.stopImmediatePropagation();const buttons=[...f.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);const d=Object.fromEntries(new FormData(f));let result;try{
if(f.id==='record-edit'){const entity=f.dataset.entity,patch={...d};delete patch.file;for(const k of ['active','archived','voided'])if(k in patch)patch[k]=patch[k]==='true';if('amount' in patch)patch.amount=Number(patch.amount);if(entity==='round'){patch.profile_ids=[...f.querySelectorAll('[name=profile_ids]:checked')].map(i=>i.value);patch.penalty_enabled=f.querySelector('[name=penalty_enabled]').checked;patch.penalty_per_day=patch.penalty_enabled?Number(f.querySelector('[name=penalty_per_day]').value):0;patch.penalty_max=patch.penalty_enabled&&f.querySelector('[name=penalty_max]').value!==''?Number(f.querySelector('[name=penalty_max]').value):null}const file=f.querySelector('[name=file]')?.files[0];if(file)validateFile(file);if(cfg.mode==='live')await api('edit-record',{entity,id:f.dataset.id,patch},file);else{const r=db[{member:'profiles',round:'rounds',expense:'expenses',payment:'payments',charge:'charges'}[entity]].find(r=>r.id===f.dataset.id);if(['round','charge'].includes(entity)&&Number(patch.amount)!==Number(r.amount)&&db.payments.some(p=>['approved','pending','review'].includes(p.status)&&(entity==='charge'?p.charge_id===r.id:(db.references?.charges||db.charges).find(c=>c.id===p.charge_id)?.round_id===r.id)))throw Error('มีการชำระแล้ว ไม่สามารถเปลี่ยนยอด');if(entity==='member'&&r.id===user.id&&(patch.role!=='admin'||!patch.active))throw Error('ไม่สามารถปิดหรือถอดสิทธิ์แอดมินของตนเอง');const before={...r};if(entity==='round'&&patch.amount!==r.amount)db.charges.filter(c=>c.round_id===r.id).forEach(c=>c.amount=patch.amount);Object.assign(r,patch);audit('แก้ไข '+entity);db.audit[0].details={before,after:{...r}}}}
if(f.id==='settings-edit'){const settings=Object.fromEntries(settingKeys.map(k=>[k,d[k]??cfg[k]??'']));const file=f.querySelector('[name=file]').files[0];if(file){validateFile(file);if(file.size>1024*1024)throw Error('QR ต้องไม่เกิน 1 MB')}if(cfg.mode==='live')await api('save-settings',{settings},file);else{if(file)settings.paymentQrUrl=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});db.settings=settings;Object.assign(cfg,settings);audit('แก้ไขการตั้งค่า')}}
if(f.id==='member-reset'){if(cfg.mode==='live')await api('reset-password',{id:f.dataset.id,password:d.password});else audit('ทดลองรีเซ็ตรหัสผ่านสมาชิก')}
if(f.id==='member-identity'){if(cfg.mode==='live')await api('change-student-id',{id:f.dataset.id,student_id:d.student_id});else{if(db.profiles.some(p=>p.id!==f.dataset.id&&p.student_id===d.student_id))throw Error('รหัสนี้มีบัญชีแล้ว');db.profiles.find(p=>p.id===f.dataset.id).student_id=d.student_id;audit('แก้รหัสนักศึกษา')}}
if(f.id==='member-assign'){if(cfg.mode==='live')await api('assign-round',{profile_id:f.dataset.id,round_id:d.round_id});else{db.charges.push({id:crypto.randomUUID(),profile_id:f.dataset.id,round_id:d.round_id,amount:round(d.round_id).amount});audit('เพิ่มสมาชิกในรอบ')}}
if(f.id==='member-import'){if(!importRows.length)throw Error('เลือกและตรวจไฟล์ CSV ก่อน');if(cfg.mode==='live')result=await api('import-members',{rows:importRows});else result={results:importRows.map(r=>{if(db.profiles.some(p=>p.student_id===r.student_id))return {student_id:r.student_id,status:'skipped',message:'มีบัญชีแล้ว'};db.profiles.push({id:crypto.randomUUID(),student_id:r.student_id,name:r.name,year:r.year,active:true,role:'member'});audit('นำเข้าสมาชิก CSV '+r.student_id);return {student_id:r.student_id,status:'created',message:'เพิ่มแล้ว'}})};importRows=[]}
await refresh();$('#dialog').close();render();toast('บันทึกเรียบร้อย');if(result)modal('ผลการนำเข้า',`<div class="table-wrap"><table><thead><tr><th>รหัสนักศึกษา</th><th>ผล</th></tr></thead><tbody>${result.results.map(r=>`<tr><td>${esc(r.student_id)}</td><td>${esc(r.message)}</td></tr>`).join('')}</tbody></table></div><p class="help">นำเข้าอีกครั้งจะข้ามบัญชีที่สร้างแล้ว</p>`)
}catch(err){f.querySelector('.form-error').innerHTML=`<p class="error" role="alert">${esc(err.message)}</p>`}finally{buttons.forEach(b=>b.disabled=false)}},true);




function fundWorkflowText(r,kind){const state=r.workflow_status||'settled';return r.voided?'ยกเลิก':state==='pending'?'รอดำเนินการ':state==='awaiting_transfer'?'รอโอนยอด':state==='other'?(r.workflow_label||'อื่น ๆ'):kind==='expense'?'จ่ายแล้ว':'รับเงินแล้ว'}
function fundWorkflowBadge(r,kind){const state=r.workflow_status||'settled',label=fundWorkflowText(r,kind);const cls=r.voided?'rejected':state==='settled'?'approved':'review';return user.role==='admin'?`<button type="button" class="ghost small fund-status-button" data-fund-status="${kind}" data-id="${esc(r.id)}" aria-label="เปลี่ยนสถานะ ${esc(r.title)}"><span class="badge ${cls}">${esc(label)} ${icon('edit')}</span></button>`:`<span class="badge ${cls}">${esc(label)}</span>`}
