'use strict';
const busyJobs=new Map();let busySerial=0,busyTimer;
function paintBusy(){let el=document.getElementById('operation-status');if(!el){el=document.createElement('div');el.id='operation-status';el.setAttribute('role','status');el.setAttribute('aria-live','polite');document.body.append(el)}const parent=document.querySelector('dialog[open]')||document.body;if(el.parentElement!==parent)parent.append(el);const job=[...busyJobs.values()].at(-1);el.hidden=!job;if(job)el.innerHTML=`<span class="operation-spinner" aria-hidden="true"></span><div><strong>${esc(job)}</strong><small>กรุณารอสักครู่</small></div>`}
function startBusy(label){const id=++busySerial;busyJobs.set(id,label);clearTimeout(busyTimer);paintBusy();return()=>{busyJobs.delete(id);if(busyJobs.size)paintBusy();else busyTimer=setTimeout(paintBusy,120)}}
const operationLabels={'bootstrap':'กำลังโหลดข้อมูล','submit-payment':'กำลังอัปโหลดและตรวจสอบสลิป','retry-payment':'กำลังตรวจสอบสลิปอีกครั้ง','review':'กำลังบันทึกผลตรวจสอบ','remind':'กำลังส่งการแจ้งเตือน','new-round':'กำลังสร้างบิล','new-member':'กำลังเพิ่มสมาชิก','save-income':'กำลังบันทึกรายรับ','new-expense':'กำลังบันทึกรายจ่าย','save-settings':'กำลังบันทึกการตั้งค่า','edit-record':'กำลังบันทึกการแก้ไข','delete-record':'กำลังย้ายเข้าถังขยะ','restore-record':'กำลังกู้คืนข้อมูล','purge-trash':'กำลังล้างถังขยะ','cleanup-preview':'กำลังนับรายการเก่า','cleanup-history':'กำลังล้างข้อมูลเก่า','link-code':'กำลังสร้างรหัสเชื่อม LINE'};
const operationsApi=api;api=async function(action,...args){const done=startBusy(operationLabels[action]||'กำลังดำเนินการ');try{return await operationsApi(action,...args)}finally{done()}};
const operationsFetch=window.fetch?.bind(window);if(operationsFetch)window.fetch=async function(input,options){const url=typeof input==='string'?input:input.url||String(input),isAuth=url.includes('/auth/v1/'),isFile=url.includes('action=download');if(!isAuth&&!isFile)return operationsFetch(input,options);const done=startBusy(isFile?'กำลังโหลดหลักฐาน':url.includes('logout')?'กำลังออกจากระบบ':url.includes('grant_type=password')?'กำลังเข้าสู่ระบบ':url.includes('/user')?'กำลังบันทึกข้อมูลบัญชี':'กำลังตรวจสอบการเข้าสู่ระบบ');try{return await operationsFetch(input,options)}finally{done()}};
new MutationObserver(records=>{for(const r of records){const b=r.target;if(b.tagName==='BUTTON'&&b.type==='submit'){const busy=b.disabled;b.classList.toggle('button-working',busy);if(busy)b.setAttribute('aria-busy','true');else b.removeAttribute('aria-busy')}}}).observe(document.body,{subtree:true,attributes:true,attributeFilter:['disabled']});
const operationsContent=content;content=function(){let html=operationsContent();if(user?.role==='admin'&&['notifications','audit'].includes(view)){const t=document.createElement('template');t.innerHTML=html;t.content.querySelector('.page-head')?.insertAdjacentHTML('beforeend',`<button class="secondary small" data-cleanup="${view}">${icon('trash')} ล้างข้อมูลเก่า</button>`);html=t.innerHTML}return html};
let cleanupPreview=null;
function cleanupModal(kind){cleanupPreview=null;modal(kind==='audit'?'ล้างประวัติกิจกรรมเก่า':'ล้างข้อความเก่า',`<form id="cleanup-form" data-kind="${kind}"><label for="cleanup-months">ลบข้อมูลที่เก่ากว่า (เดือน)</label><input id="cleanup-months" name="months" type="number" min="1" max="120" step="1" value="6" required><p class="help">นับย้อนหลังเป็นเดือนปฏิทินตามเวลาไทย เลือกได้ 1–120 เดือน</p><div id="cleanup-preview"></div><div class="actions"><button type="button" class="secondary" data-action="close">ยกเลิก</button><button type="submit">ตรวจสอบจำนวนรายการ</button></div><div class="form-error"></div></form>`)}
document.addEventListener('click',e=>{const b=e.target.closest('[data-cleanup]');if(b&&user?.role==='admin')cleanupModal(b.dataset.cleanup)});
document.addEventListener('input',e=>{if(e.target.id!=='cleanup-months')return;cleanupPreview=null;document.getElementById('cleanup-preview').innerHTML='';const b=e.target.form.querySelector('[type=submit]');b.textContent='ตรวจสอบจำนวนรายการ';b.classList.remove('danger');b.disabled=false});
function demoCutoff(months){const now=new Date(),parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(now).split('-').map(Number);const d=new Date(Date.UTC(parts[0],parts[1]-1-months,1));const day=Math.min(parts[2],new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate());d.setUTCDate(day);return new Date(d.getTime()-7*3600000).toISOString()}
document.addEventListener('submit',async e=>{const f=e.target;if(f.id!=='cleanup-form')return;e.preventDefault();e.stopImmediatePropagation();const submit=f.querySelector('[type=submit]'),months=Number(f.elements.months.value),kind=f.dataset.kind;const buttons=[...f.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);f.elements.months.disabled=true;try{if(user.role!=='admin')throw Error('ไม่มีสิทธิ์ดำเนินการ');if(!Number.isInteger(months)||months<1||months>120)throw Error('เลือกจำนวนเดือน 1–120');if(!cleanupPreview){const result=cfg.mode==='live'?await api('cleanup-preview',{kind,months}):{cutoff:demoCutoff(months),anchor:new Date().toISOString(),count:db[kind].filter(x=>Date.parse(x.created_at)<Date.parse(demoCutoff(months))).length};cleanupPreview={...result,kind,months};document.getElementById('cleanup-preview').innerHTML=`<div class="cleanup-summary"><span>ข้อมูลก่อนวันที่ ${date(result.cutoff)}</span><strong>${Number(result.count).toLocaleString('th-TH')} รายการ</strong><p>${kind==='audit'?'ประวัติกิจกรรม':'ข้อความแจ้งเตือน'}ที่เข้าเกณฑ์จะถูกลบถาวร ไม่กระทบยอดเงิน บิล หรือหลักฐานชำระเงิน${kind==='notifications'?' และไม่ลบข้อความที่ส่งไปใน LINE แล้ว':''}</p></div>`;submit.textContent=result.count?'ยืนยันลบข้อมูลเก่า':'ไม่มีรายการที่ต้องลบ';submit.classList.toggle('danger',result.count>0)}else{let count;if(cfg.mode==='live'){const result=await api('cleanup-history',{kind,months,anchor:cleanupPreview.anchor,confirmation:'ลบข้อมูล'});count=result.count}else{count=cleanupPreview.count;db[kind]=db[kind].filter(x=>Date.parse(x.created_at)>=Date.parse(cleanupPreview.cutoff));audit('ล้างข้อมูลเก่า '+count+' รายการ')}await refresh();$('#dialog').close();render();toast(`ล้างข้อมูลเก่าแล้ว ${count} รายการ`);cleanupPreview=null}}catch(err){if(cleanupPreview){cleanupPreview=null;submit.textContent='ตรวจสอบจำนวนรายการอีกครั้ง';submit.classList.remove('danger')}f.querySelector('.form-error').innerHTML=`<p class="error" role="alert">${esc(err.message)}</p>`}finally{buttons.forEach(b=>b.disabled=false);f.elements.months.disabled=false;if(cleanupPreview?.count===0)submit.disabled=true}},true);
