'use strict';
const entityTables={member:'profiles',round:'rounds',charge:'charges',payment:'payments',expense:'expenses',income:'incomes'};
const entityLabels={member:'ผู้ใช้',round:'รายการบิล',charge:'รายการเรียกเก็บ',payment:'การชำระเงิน',expense:'รายจ่าย',income:'รายรับเพิ่มเติม'};
const referenceRows=k=>db?.references?.[k]||db?.[k]||[];
const withReferences=fn=>{const charges=db.charges,profiles=db.profiles;db.charges=referenceRows('charges');db.profiles=referenceRows('profiles');try{return fn()}finally{db.charges=charges;db.profiles=profiles}};
const proofHtml=(kind,r,large=false)=>r.drive_file_id?`<figure class="evidence ${large?'evidence-large':''}"><img data-proof-kind="${kind}" data-proof-id="${esc(r.id)}" alt="${kind==='payment'?'สลิปโอนเงิน':'หลักฐานรายจ่าย'}" decoding="async"><figcaption class="help" role="status">กำลังโหลดหลักฐาน…</figcaption></figure>`:r.preview?`<figure class="evidence ${large?'evidence-large':''}"><img src="${esc(r.preview)}" alt="หลักฐานตัวอย่าง"></figure>`:'<span class="help">ไม่มีหลักฐานแนบ</span>';
const previousPaymentTable=paymentTable;
paymentTable=function(payments,review=false){const html=withReferences(()=>previousPaymentTable(payments,review));if(!payments.length)return html;const template=document.createElement('template');template.innerHTML=html;template.content.querySelectorAll('tbody tr').forEach((tr,i)=>{if(user.role==='admin'){const actions=tr.querySelector('td:nth-child(4)');actions?.insertAdjacentHTML('beforeend',deleteButton('payment',payments[i].id))}});return template.innerHTML};
const previousReceipt=receipt;receipt=id=>withReferences(()=>previousReceipt(id));
const previousReviewModal=reviewModal;
reviewModal=function(id){withReferences(()=>previousReviewModal(id));const p=db.payments.find(p=>p.id===id);if(!p)return;const button=$('#dialog [data-payment-file]');if(button)button.closest('p').outerHTML=proofHtml('payment',p,true);$('#dialog').insertAdjacentHTML('beforeend',`<div class="actions">${deleteButton('payment',id)}</div>`);watchProofs()};
const deleteButton=(entity,id)=>`<button class="danger small" data-delete-entity="${entity}" data-delete-id="${esc(id)}">ลบ</button>`;
const previousRecordContent=content;
content=function(){if(user?.role==='admin'&&view==='trash'){const entries=Object.entries(db.trash||{}).flatMap(([entity,rows])=>rows.map(r=>({entity,r})));return head('ถังขยะ','กู้คืนได้ภายใน 30 วัน หลังจากนั้นลบถาวรอัตโนมัติ')+panel('รายการที่ลบ',entries.length?`<div class="table-wrap"><table><thead><tr><th>ประเภท</th><th>รายการ</th><th>วันที่ลบ</th><th></th></tr></thead><tbody>${entries.map(({entity,r})=>`<tr><td>${entityLabels[entity]}</td><td>${esc(recordTitle(entity,r))}${r.amount?`<small>฿${money(r.amount)}</small>`:''}</td><td>${dateTime(r.deleted_at)}</td><td><button class="secondary small" data-restore-entity="${entity}" data-restore-id="${esc(r.id)}">กู้คืน</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">ถังขยะว่าง</div>')}
let html=previousRecordContent();return html};
function recordTitle(entity,r){if(entity==='member')return `${r.name} · ${r.student_id}`;if(entity==='round'||entity==='expense'||entity==='income')return r.title;const c=entity==='charge'?r:referenceRows('charges').find(c=>c.id===r.charge_id),p=referenceRows('profiles').find(p=>p.id===(r.profile_id||c?.profile_id));return `${p?.name||'ผู้ใช้เดิม'} · ${round(c?.round_id).title||'รายการเดิม'}`}
const previousRecordsRender=render;let previousUserScope=null;
render=function(){const scope=user?user.id+'|'+user.role:null;if(scope!==previousUserScope){if($('#dialog').open)$('#dialog').close();$('#dialog').innerHTML='';selectedDeletion=null;previousUserScope=scope}releaseProofs();previousRecordsRender();if(!user)return;if(user.role==='admin'){
 const navEl=$('.nav');navEl?.insertAdjacentHTML('beforeend',`<button data-view="trash" class="${view==='trash'?'active':''}">${icon('history')}ถังขยะ</button>`);
 document.querySelectorAll('#app [data-edit]').forEach(b=>{if(b.dataset.edit==='member'&&b.dataset.id===user.id)return;b.insertAdjacentHTML('afterend',deleteButton(b.dataset.edit,b.dataset.id))});
 const map={members:'member',rounds:'round',review:'payment',fund:'expense',reports:'charge'},entity=map[view];if(entity){const rows=pageRecords(entity);if(rows.length)document.querySelector('.page-head')?.insertAdjacentHTML('beforeend',`<button class="danger small" data-delete-page="${entity}">ลบทั้งหมดในหน้านี้ (${Math.min(rows.length,500)})</button>`)}
 document.querySelectorAll('#app [data-expense-file]').forEach(b=>{const r=db.expenses.find(r=>r.id===b.dataset.expenseFile);if(r)b.outerHTML=proofHtml('expense',r)});
 }watchProofs()};
function pageRecords(entity){let rows=db[entityTables[entity]]||[];if(entity==='member')rows=rows.filter(r=>r.id!==user.id&&(r.name.includes(filter)||r.student_id.includes(filter)));if(entity==='payment'&&view==='review')rows=rows.filter(r=>statusFilter==='all'||r.status===statusFilter);if(entity==='charge'&&view==='reports')rows=reportCharges();return rows}
let selectedDeletion=null;
function deletionModal(entity,ids,deleted=true){if(user.role!=='admin'||!ids.length)return;selectedDeletion={entity,ids:ids.slice(0,500),deleted};const rows=deleted?db[entityTables[entity]]:(db.trash?.[entity]||[]);const labels=selectedDeletion.ids.map(id=>recordTitle(entity,rows.find(r=>r.id===id)||{}));const impacts={member:'บัญชีจะเข้าเว็บไม่ได้ และรายการค้างจะซ่อนจากหน้าปกติ ประวัติเงินที่รับแล้วจะยังอยู่',round:'บิลและรายการเรียกเก็บในบิลจะซ่อนและหยุดรับชำระ ประวัติเงินที่รับแล้วจะยังอยู่',charge:'รายการเรียกเก็บจะซ่อนและหยุดรับชำระ ประวัติเงินที่รับแล้วจะยังอยู่',payment:'รายการจะซ่อน ยอดรับที่ยืนยันแล้วจะลดลง และยอดค้างจะคำนวณใหม่',income:'รายรับจะซ่อนและไม่นับในยอดกองกลาง',expense:'รายจ่ายจะซ่อนและไม่นับในยอดกองกลาง'};modal(deleted?'ยืนยันลบรายการ':'กู้คืนรายการ',`<p>${deleted?'ลบ':'กู้คืน'} ${entityLabels[entity]} ${selectedDeletion.ids.length} รายการ</p><ul class="deletion-list">${labels.slice(0,8).map(t=>`<li>${esc(t)}</li>`).join('')}${labels.length>8?'<li>และรายการที่เหลือ</li>':''}</ul><p class="note">${deleted?impacts[entity]+' · กู้คืนได้จากถังขยะ':entity==='payment'?'การกู้คืนจะตรวจยอดและรายการรอตรวจซ้ำ หากเกินยอดจะไม่อนุญาต':'ถ้าบิลหรือผู้ใช้ที่เกี่ยวข้องยังถูกลบ ให้กู้คืนรายการนั้นก่อนเพื่อให้ข้อมูลปรากฏ'}</p><form id="record-delete">${inputField('reason',deleted?'เหตุผลที่ลบ':'เหตุผลที่กู้คืน','','text','required maxlength="500"')}<div class="actions"><button type="button" class="secondary" data-action="close">ยกเลิก</button><button type="submit" class="${deleted?'danger':''}">${deleted?'ยืนยันลบ':'ยืนยันกู้คืน'}</button></div><div class="form-error"></div></form>`)}
const previousEditRecord=editRecord;
editRecord=function(entity,id){previousEditRecord(entity,id);if(entity==='expense'){const expense=db.expenses.find(r=>r.id===id);if(expense){$('#record-edit').insertAdjacentHTML('afterbegin',proofHtml('expense',expense,true));watchProofs()}}if(entity!=='member')return;const p=db.profiles.find(p=>p.id===id);if(!p)return;const actions=$('#record-edit .actions');actions.insertAdjacentHTML('beforebegin',inputField('phone','เบอร์โทรศัพท์',p.phone||'','tel','maxlength="30"')+inputField('contact_email','อีเมลติดต่อ',p.contact_email||'','email','maxlength="254"')+inputField('profile_note','หมายเหตุผู้ใช้ (เฉพาะแอดมิน)',p.profile_note||'','text','maxlength="1000"'));$('#dialog').insertAdjacentHTML('beforeend',`<div class="actions"><button class="secondary small" data-identity="${esc(id)}">แก้รหัสนักศึกษา</button>${id===user.id?'<button class="secondary small" data-action="password">เปลี่ยนรหัสผ่านของฉัน</button>':`<button class="secondary small" data-reset="${esc(id)}">รีเซ็ตรหัสผ่าน</button>`}${p.line_linked?`<button class="secondary small" data-unlink-line="${esc(id)}">ยกเลิกเชื่อม LINE</button>`:''}</div>`)};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.deleteEntity)deletionModal(b.dataset.deleteEntity,[b.dataset.deleteId]);if(b.dataset.restoreEntity)deletionModal(b.dataset.restoreEntity,[b.dataset.restoreId],false);if(b.dataset.deletePage)deletionModal(b.dataset.deletePage,pageRecords(b.dataset.deletePage).map(r=>r.id));if(b.dataset.unlinkLine){const p=db.profiles.find(p=>p.id===b.dataset.unlinkLine);modal('ยกเลิกเชื่อม LINE',`<p>ยกเลิกการส่งข้อความถึง LINE ของ ${esc(p.name)} สมาชิกสามารถเชื่อมใหม่ได้จากโปรไฟล์</p><form id="line-unlink" data-id="${esc(p.id)}"><div class="actions"><button type="submit" class="danger">ยืนยันยกเลิกเชื่อม</button></div><div class="form-error"></div></form>`)}});
document.addEventListener('submit',async e=>{const f=e.target;if(!['record-delete','self-profile','line-unlink'].includes(f.id))return;e.preventDefault();e.stopImmediatePropagation();const d=Object.fromEntries(new FormData(f)),buttons=[...f.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{
 if(f.id==='record-delete'){if(!selectedDeletion)throw Error('เลือกข้อมูลใหม่อีกครั้ง');const operation={...selectedDeletion,reason:d.reason};if(cfg.mode==='live')await api('delete-records',operation);else{db.references??={rounds:[...db.rounds],charges:[...db.charges],profiles:[...db.profiles]};db.trash??={};const table=entityTables[operation.entity];db.trash[operation.entity]??=[];for(const id of operation.ids){if(operation.entity==='member'&&id===user.id)throw Error('ไม่สามารถลบบัญชีของตนเอง');if(operation.deleted){const r=db[table].find(r=>r.id===id);if(r){r.deleted_at=new Date().toISOString();db.trash[operation.entity].push(r);db[table]=db[table].filter(r=>r.id!==id)}}else{const r=db.trash[operation.entity].find(r=>r.id===id);if(r){r.deleted_at=null;db[table].push(r);db.trash[operation.entity]=db.trash[operation.entity].filter(r=>r.id!==id)}}}audit((operation.deleted?'ลบ ':'กู้คืน ')+operation.entity)}selectedDeletion=null}
 if(f.id==='self-profile'){if(cfg.mode==='live')await api('edit-self',d);else{Object.assign(user,d);audit('แก้ไขโปรไฟล์ของตนเอง')}}
 if(f.id==='line-unlink'){if(cfg.mode==='live')await api('unlink-line',{id:f.dataset.id});else{db.profiles.find(p=>p.id===f.dataset.id).line_linked=false;audit('ยกเลิกเชื่อม LINE')}}
 await refresh();$('#dialog').close();render();toast('บันทึกเรียบร้อย');
 }catch(err){f.querySelector('.form-error').innerHTML=`<p class="error" role="alert">${esc(err.message)}</p>`}finally{buttons.forEach(b=>b.disabled=false)}},true);
// Fetch private Drive evidence with authorization headers; URLs contain no tokens.
let proofObserver=null,proofQueue=[],proofLoading=0;const proofResources=new Map();
function releaseProofs(){proofObserver?.disconnect();proofQueue=[];for(const [img,r] of proofResources){r.controller?.abort();if(r.url)URL.revokeObjectURL(r.url)}proofResources.clear()}
function queueProof(img){if(proofResources.has(img))return;proofResources.set(img,{});proofQueue.push(img);pumpProofs()}
function pumpProofs(){while(proofLoading<3&&proofQueue.length){const img=proofQueue.shift();if(!img.isConnected){proofResources.delete(img);continue}proofLoading++;loadProof(img).finally(()=>{proofLoading--;pumpProofs()})}}
async function loadProof(img){const controller=new AbortController(),entry=proofResources.get(img);entry.controller=controller;const caption=img.parentElement.querySelector('figcaption');try{const res=await fetch(`${cfg.supabaseUrl}/functions/v1/finance-api?action=download&kind=${encodeURIComponent(img.dataset.proofKind)}&id=${encodeURIComponent(img.dataset.proofId)}`,{headers:{Authorization:`Bearer ${token}`,apikey:cfg.supabaseAnonKey},signal:controller.signal});if(!res.ok)throw Error('โหลดหลักฐานไม่สำเร็จ');const blob=await res.blob();if(!['image/jpeg','image/png','image/webp'].includes(blob.type))throw Error('รูปแบบหลักฐานไม่รองรับ');if(!img.isConnected||controller.signal.aborted)return;entry.url=URL.createObjectURL(blob);img.src=entry.url;caption.textContent='';img.onload=()=>{caption.textContent='';img.classList.add('loaded')};img.onerror=()=>{caption.textContent='แสดงภาพไม่สำเร็จ'};}catch(err){if(err.name!=='AbortError'&&img.isConnected){caption.textContent='โหลดหลักฐานไม่ได้ กรุณารีเฟรชหรือเข้าสู่ระบบใหม่';img.hidden=true}}}
function watchProofs(){for(const [img,r] of proofResources)if(!img.isConnected){r.controller?.abort();if(r.url)URL.revokeObjectURL(r.url);proofResources.delete(img)}if(cfg.mode!=='live')return;proofObserver?.disconnect();const images=[...document.querySelectorAll('img[data-proof-id]')].filter(img=>!proofResources.has(img));if(typeof IntersectionObserver==='undefined'){images.forEach(queueProof);return}proofObserver=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){proofObserver.unobserve(e.target);queueProof(e.target)}},{rootMargin:'180px'});images.forEach(img=>{if(img.closest('dialog[open]'))queueProof(img);else proofObserver.observe(img)})}
document.querySelector('#dialog').addEventListener('close',()=>queueMicrotask(()=>{if($('#dialog').open)return;for(const [img,r] of proofResources)if(img.closest('#dialog')){r.controller?.abort();if(r.url)URL.revokeObjectURL(r.url);img.removeAttribute('src');proofResources.delete(img)}}));



