'use strict';
(()=>{const cfg=window.FINANCE_CONFIG,form=document.getElementById('register-form'),status=document.getElementById('register-status'),token=new URLSearchParams(location.hash.slice(1)).get('token');let batchMode=false,session=null,studentId=null;const lookup=document.getElementById('student-lookup'),line=document.getElementById('registration-line');history.replaceState(null,'',location.pathname+location.search);document.getElementById('register-support').href=/^https:\/\/(lin\.ee|line\.me)\//.test(cfg.lineOaUrl||'')?cfg.lineOaUrl:'https://lin.ee/7VYJbx0';
async function request(action,data={}){const r=await fetch(cfg.supabaseUrl+'/functions/v1/account-access',{method:'POST',headers:{apikey:cfg.supabaseAnonKey,'Content-Type':'application/json'},body:JSON.stringify({action,token,...data})});const j=await r.json();if(!r.ok)throw Error(j.error||'ดำเนินการไม่สำเร็จ');return j}
if(!token||!/^[0-9a-f]{64}$/.test(token)){status.textContent='ลิงก์ไม่ถูกต้อง กรุณาขอลิงก์จากผู้ดูแลระบบ';return}
request('invite-preview').then(({invite,batch})=>{batchMode=!!batch;const data=batch||invite;document.getElementById('invite-expiry').textContent='ลิงก์หมดอายุ '+new Date(data.expires_at).toLocaleString('th-TH',{timeZone:'Asia/Bangkok'});if(batchMode){status.textContent='กรอกรหัสนักศึกษาที่ผู้ดูแลระบบเตรียมไว้';lookup.hidden=false}else{document.getElementById('invite-person').textContent=invite.name_prefix+invite.first_name+' '+invite.last_name+' · '+invite.student_id;status.textContent='ข้อมูลประจำตัวกำหนดโดยผู้ดูแลระบบ';form.hidden=false}}).catch(e=>status.textContent=e.message);
lookup.addEventListener('submit',async e=>{e.preventDefault();const b=lookup.querySelector('button');if(b.disabled)return;b.disabled=true;status.textContent='กำลังตรวจสอบรายชื่อ…';try{studentId=lookup.elements.student_id.value.trim();const result=await request('batch-start',{student_id:studentId});session=result.session;document.getElementById('invite-person').textContent=result.person.name+' · '+result.person.student_id;document.getElementById('registration-code').textContent='สมัคร '+result.code;document.getElementById('registration-line-link').href=document.getElementById('register-support').href;lookup.hidden=true;line.hidden=false;status.textContent='ตรวจชื่อของคุณ แล้วส่งรหัสเชื่อม LINE เพื่อดำเนินการต่อ'}catch(err){status.textContent=err.message}finally{b.disabled=false}});
document.getElementById('registration-copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(document.getElementById('registration-code').textContent);status.textContent='คัดลอกแล้ว นำไปส่งใน LINE OA'}catch{status.textContent='กรุณาคัดลอกข้อความที่แสดงแล้วส่งใน LINE OA'}});
document.getElementById('registration-check').addEventListener('click',async e=>{const b=e.currentTarget;b.disabled=true;status.textContent='กำลังตรวจสอบ LINE…';try{const result=await request('batch-state',{student_id:studentId,session});if(result.linked){line.hidden=true;form.hidden=false;status.textContent='เชื่อม LINE แล้ว ตั้งรหัสผ่านเพื่อเปิดใช้งานบัญชี';form.elements.password.focus()}else status.textContent='ยังไม่ได้รับการยืนยัน กรุณาส่งข้อความใน LINE OA แล้วตรวจสอบอีกครั้ง'}catch(err){status.textContent=err.message}finally{b.disabled=false}});
form.addEventListener('submit',async e=>{e.preventDefault();if(form.dataset.saving)return;const password=form.elements.password.value;if(password.length<6||password.length>128){status.textContent='รหัสผ่านต้องมี 6–128 ตัวอักษร';return}if(password!==form.elements.confirm.value){status.textContent='รหัสผ่านทั้งสองช่องไม่ตรงกัน';return}form.dataset.saving='true';const button=form.querySelector('button');button.disabled=true;status.textContent='กำลังสร้างบัญชี…';try{await request(batchMode?'batch-accept':'invite-accept',{password,...(batchMode?{student_id:studentId,session}:{})});form.reset();form.hidden=true;status.textContent='สร้างบัญชีสำเร็จ เข้าสู่ระบบด้วยรหัสนักศึกษาและรหัสผ่านที่ตั้งได้เลย'}catch(e){status.textContent=e.message}finally{button.disabled=false;delete form.dataset.saving}})})();
