'use strict';
const sessionKey='finance-medtech-session-v1';let loginSession=null,sessionPersistent=true,sessionFlight=null,sessionTimer=null,sessionGeneration=0;
function persistLoginSession(){try{if(loginSession){(sessionPersistent?localStorage:sessionStorage).setItem(sessionKey,JSON.stringify(loginSession));(sessionPersistent?sessionStorage:localStorage).removeItem(sessionKey)}else{localStorage.removeItem(sessionKey);sessionStorage.removeItem(sessionKey)}}catch{}}
function setLoginSession(s,remember=true){sessionPersistent=remember;loginSession={access_token:s.access_token,refresh_token:s.refresh_token,expires_at:s.expires_at||Math.floor(Date.now()/1000)+(s.expires_in||3600)};token=loginSession.access_token;persistLoginSession();scheduleSessionRefresh()}
function clearLoginSession(){sessionGeneration++;loginSession=null;token=null;clearTimeout(sessionTimer);persistLoginSession()}
function scheduleSessionRefresh(){clearTimeout(sessionTimer);if(loginSession)sessionTimer=setTimeout(()=>ensureLiveSession().catch(()=>{}),Math.max(1000,(loginSession.expires_at*1000-Date.now())-45000))}
async function ensureLiveSession(){if(cfg.mode!=='live'||!loginSession)return;if(loginSession.expires_at*1000-Date.now()>60000){token=loginSession.access_token;return}if(sessionFlight)return sessionFlight;const generation=sessionGeneration;sessionFlight=(async()=>{try{const r=await fetch(`${cfg.supabaseUrl}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:cfg.supabaseAnonKey,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:loginSession.refresh_token})});if(!r.ok){if(r.status===400||r.status===401){clearLoginSession();user=null;render()}throw Error('เซสชันหมดอายุ กรุณาเข้าสู่ระบบใหม่')}const j=await r.json();if(generation===sessionGeneration)setLoginSession(j,sessionPersistent)}catch(e){if(loginSession)sessionTimer=setTimeout(()=>ensureLiveSession().catch(()=>{}),30000);throw e}finally{sessionFlight=null}})();return sessionFlight}
async function logoutSession(){const oldToken=token;clearLoginSession();user=null;render();if(cfg.mode==='live'&&oldToken)try{await fetch(`${cfg.supabaseUrl}/auth/v1/logout?scope=local`,{method:'POST',headers:{apikey:cfg.supabaseAnonKey,Authorization:`Bearer ${oldToken}`}})}catch{}}
async function restoreLoginSession(){if(cfg.mode!=='live')return;try{const local=localStorage.getItem(sessionKey),stored=local||sessionStorage.getItem(sessionKey);if(!stored)return;const s=JSON.parse(stored);if(!s.access_token||!s.refresh_token||!Number.isFinite(s.expires_at))throw Error('Invalid session');loginSession=s;sessionPersistent=!!local;token=s.access_token;await ensureLiveSession();await refresh();view='dashboard';render();scheduleSessionRefresh()}catch(e){if(loginSession&&loginSession.expires_at*1000>Date.now()&&!e.status){toast('เชื่อมต่อไม่สำเร็จ กรุณารีเฟรชเพื่อลองอีกครั้ง');return}clearLoginSession();user=null;render()}}
window.addEventListener('storage',e=>{if(e.key!==sessionKey)return;if(!e.newValue){clearLoginSession();user=null;render()}else{try{loginSession=JSON.parse(e.newValue);token=loginSession.access_token;scheduleSessionRefresh()}catch{}}});
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&user)ensureLiveSession().catch(()=>{})});
function latestPaymentHistory(rows){const groups=new Map();for(const p of rows){const key=p.profile_id+'|'+(p.charge_id||p.id);const previous=groups.get(key);const stamp=Date.parse(p.created_at)||0;if(!previous||stamp>=(Date.parse(previous.created_at)||0))groups.set(key,p)}return [...groups.values()].sort((a,b)=>(Date.parse(b.created_at)||0)-(Date.parse(a.created_at)||0))}
const historyContent=content;content=function(){if(view!=='history')return historyContent();const rows=latestPaymentHistory(db.payments.filter(p=>p.profile_id===user.id));return head('ประวัติการชำระ','แสดงรายการล่าสุดของแต่ละบิล')+panel('การชำระเงิน',paymentTable(rows))};
const historyPaymentTable=paymentTable;paymentTable=function(rows,review=false){let html=historyPaymentTable(rows,review);if(view!=='history')return html;const t=document.createElement('template');t.innerHTML=html;t.content.querySelectorAll('tbody tr').forEach((tr,i)=>{const p=rows[i];if(!p)return;const actions=tr.querySelector('td:last-child');if(p.drive_file_id||p.preview)actions?.insertAdjacentHTML('beforeend',`<button class="secondary small" data-history-proof="${esc(p.id)}" aria-label="ดูหลักฐาน">ดูหลักฐาน</button>`)});return t.innerHTML};
document.addEventListener('click',e=>{const b=e.target.closest('[data-history-proof]');if(!b)return;const p=db.payments.find(p=>p.id===b.dataset.historyProof&&p.profile_id===user.id);if(!p)return;modal('หลักฐานการชำระเงิน',`<p>฿${money(p.amount)} · ${esc(labels[p.status])} · ${date(p.created_at)}</p>${proofHtml('payment',p,true)}`);ensureLiveSession().then(watchProofs).catch(e=>toast(e.message))});
restoreLoginSession();
